name: foodorder
version: 2.6.6+125
publish_to: none
description: A new Fanxing Food Order Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.7.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  package_info: ^2.0.2
  fluttertoast: ^8.2.2
  sqflite: ^2.0.2
  cached_network_image: ^3.2.0
  event_bus: ^2.0.0
  flutter_easyloading: ^3.0.5
  permission_handler: ^10.0.0
  firebase_analytics: ^10.5.0
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  open_file: ^3.2.1
  path_provider: ^2.0.11
  crypto: ^3.0.2
  assets_audio_player: 3.0.6
  widget_to_image: ^2.0.0
  auto_size_text: ^3.0.0
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  image: ^3.0.2
  get_storage: ^2.1.1
  flutter_swiper_plus: ^2.0.4
  google_fonts: ^4.0.4
  flutter_printer_plus: ^0.0.2+2
  badges: ^3.1.1
  connectivity_plus: ^4.0.2
  get: 4.6.5
  intl: ^0.17.0
  archive: ^3.3.0
  transparent_image: ^2.0.1
  animated_widgets: ^1.1.0
  flutter: 
    sdk: flutter
  paycube: 
    path: ./lib/app/plugins/paycube
  paycube_old:
    path: ./lib/app/plugins/paycube_old
  flutter_plugin_msprinter: 
    path: ./lib/app/plugins/flutter_plugin_msprint
  appset: 
    path: ./lib/app/plugins/appset
  #widget_to_image:
    #path: ./lib/app/plugins/widget_to_image-main

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/public/
    - assets/images/error/
    - assets/images/kanran/
    - assets/images/sanfeng/
    - assets/images/rijindoujin/
    - assets/images/ichixianjia/
    - assets/images/gongcha/
    - assets/audios/
  fonts: 
    - family: KoruriLightNew
      fonts: 
        - asset: assets/fonts/Work_Sans/Koruri-Light-new.ttf

    - family: NotoSansJP
      fonts: 
        - asset: assets/fonts/Work_Sans/JP/NotoSansJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Work_Sans/JP/NotoSansJP-Light.otf
          weight: 300
        - asset: assets/fonts/Work_Sans/JP/NotoSansJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Work_Sans/JP/NotoSansJP-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/JP/NotoSansJP-SemiBold.ttf
          weight: 600

    - family: NotoSansCN
      fonts:
        - asset: assets/fonts/Work_Sans/CN/NotoSansSC-Thin.ttf
          weight: 100
        - asset: assets/fonts/Work_Sans/CN/NotoSansSC-Light.ttf
          weight: 300
        - asset: assets/fonts/Work_Sans/CN/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/Work_Sans/CN/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/CN/NotoSansSC-SemiBold.ttf
          weight: 600

    - family: NotoSans
      fonts:
      - asset: assets/fonts/Work_Sans/EN/NotoSans-Thin.ttf
        weight: 100
      - asset: assets/fonts/Work_Sans/EN/NotoSans-Light.ttf
        weight: 300
      - asset: assets/fonts/Work_Sans/EN/NotoSans-Regular.ttf
        weight: 400
      - asset: assets/fonts/Work_Sans/EN/NotoSans-Medium.ttf
        weight: 500
      - asset: assets/fonts/Work_Sans/EN/NotoSans-SemiBold.ttf
        weight: 600
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/Work_Sans/KR/NotoSansKR-Thin.ttf
          weight: 100
        - asset: assets/fonts/Work_Sans/KR/NotoSansKR-Light.ttf
          weight: 300
        - asset: assets/fonts/Work_Sans/KR/NotoSansKR-Regular.ttf
          weight: 400
        - asset: assets/fonts/Work_Sans/KR/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/KR/NotoSansKR-SemiBold.ttf
          weight: 600

    - family: UbuntuMonoRegular
      fonts: 
        - asset: assets/fonts/Work_Sans/UbuntuMono-Regular.ttf
    - family: ZenKakuGothicAntique
      fonts: 
        - asset: assets/fonts/Work_Sans/ZenKakuGothicAntique-Light.ttf
        - asset: assets/fonts/Work_Sans/ZenKakuGothicAntique-Regular.ttf
    - family: smartwebW1
      fonts: 
        - asset: assets/fonts/Work_Sans/bW1.ttc
  uses-material-design: true

