name: foodorder
version: 2.1.0+76
publish_to: none
description: A new Fanxing Food Order Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.5
  flutter_screenutil: ^5.7.0
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  package_info: ^2.0.2
  fluttertoast: ^8.2.2
  sqflite: ^2.0.2
  cached_network_image: ^3.2.0
  event_bus: ^2.0.0
  flutter_easyloading: ^3.0.5
  permission_handler: ^10.0.0
  firebase_analytics: ^10.1.3
  firebase_core: ^2.6.1
  firebase_crashlytics: ^3.0.14
  open_file: ^3.2.1
  path_provider: ^2.0.11
  crypto: ^3.0.2
  assets_audio_player: 3.0.6
  widget_to_image: ^2.0.0
  auto_size_text: ^3.0.0
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  image: ^3.0.2
  get_storage: ^2.1.1
  flutter_swiper_plus: ^2.0.4
  google_fonts: ^4.0.4
  flutter_printer_plus: ^0.0.2+2
  badges: ^3.1.1
  connectivity_plus: ^4.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  paycube: 
    path: ./lib/app/plugins/paycube
  flutter_plugin_msprinter: 
    path: ./lib/app/plugins/flutter_plugin_msprint
  appset: 
    path: ./lib/app/plugins/appset
  #widget_to_image:
    #path: ./lib/app/plugins/widget_to_image-main

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/public/
    - assets/images/kanran/
    - assets/images/sanfeng/
    - assets/images/rijindoujin/
    - assets/images/ichixianjia/
    - assets/images/gongcha/
    - assets/audios/
  fonts: 
    - family: KoruriLightNew
      fonts: 
        - asset: assets/fonts/Work_Sans/Koruri-Light-new.ttf
    - family: NotoSansJP
      fonts: 
        - asset: assets/fonts/Work_Sans/NotoSansJP-Thin.otf
        - asset: assets/fonts/Work_Sans/NotoSansJP-Light.otf
        - asset: assets/fonts/Work_Sans/NotoSansJP-Regular.otf
    - family: UbuntuMonoRegular
      fonts: 
        - asset: assets/fonts/Work_Sans/UbuntuMono-Regular.ttf
    - family: ZenKakuGothicAntique
      fonts: 
        - asset: assets/fonts/Work_Sans/ZenKakuGothicAntique-Light.ttf
        - asset: assets/fonts/Work_Sans/ZenKakuGothicAntique-Regular.ttf
    - family: smartwebW1
      fonts: 
        - asset: assets/fonts/Work_Sans/bW1.ttc
  uses-material-design: true

