class GImage{
  static String getImageString(String shopInfo, String stringTag) {
    // 图片data包
    var imagePack;
    if (shopInfo == 'kanran') {
      imagePack = {
        "backbutton_top":"assets/images/kanran/backbutton_top.png",
        "backloading":"assets/images/kanran/backloading.gif",
        "btn001":"assets/images/kanran/btn001.png",
        "btn002":"assets/images/kanran/btn002.png",
        "cargo_loading":"assets/images/public/cargo_loading.gif",
        "cart_bottom":"assets/images/kanran/cart_bottom.png",
        "category_selected":"assets/images/kanran/category_selected.png",
        "category_unselected":"assets/images/kanran/category_unselected.png",
        "checked_green":"assets/images/kanran/checked_green.png",
        "delOne":"assets/images/kanran/delOne.png",
        "dialog_close":"assets/images/kanran/dialog_close.png",
        "down":"assets/images/kanran/down.png",
        "home_button":"assets/images/kanran/home_button.png",
        "home":"assets/images/kanran/home.png",
        "load_error":"assets/images/kanran/load_error.png",
        "load_nodata":"assets/images/kanran/load_nodata.png",
        "logo":"assets/images/kanran/logo.png",
        "menu_up":"assets/images/kanran/menu_up.png",
        "newloading":"assets/images/sanfeng/newloading.gif",
        "optionChecked":"assets/images/kanran/optionChecked.png",
        "price_tag":"assets/images/kanran/price_tag.png",
        "price_subtraction_tag":"assets/images/sanfeng/price_subtraction_tag.png",
        "printticket":"assets/images/kanran/printticket.gif",
        "printticketloading":"assets/images/kanran/printticketloading.gif",
        "public_dingshi_option":"assets/images/kanran/public_dingshi_option.png",
        "public_dingshi_submit":"assets/images/kanran/public_dingshi_submit.png",
        "public_index_option":"assets/images/kanran/public_index_option.png",
        "public_index_submit":"assets/images/kanran/public_index_submit.png",
        "redDafen":"assets/images/kanran/redDafen.png",
        "redPutong":"assets/images/kanran/redPutong.png",
        "saoma":"assets/images/public/saoma.jpg",
        "settlement_alipay":"assets/images/kanran/settlement_alipay.png",
        "settlement_back":"assets/images/kanran/settlement_back.png",
        "settlement_cash":"assets/images/kanran/settlement_cash.png",
        "settlement_paypay":"assets/images/kanran/settlement_paypay.png",
        "settlement_tag":"assets/images/kanran/settlement_tag.png",
        "settlement_wechat":"assets/images/kanran/settlement_wechat.png",
        "shouqing_jpep":"assets/images/kanran/shouqing.jpeg",
        "shouqing_png":"assets/images/kanran/shouqing.png",
        "up":"assets/images/kanran/up.png",
        "xianjin":"assets/images/public/xianjin.jpg",
        "qiandaobutton":"assets/images/kanran/qiandaobutton.png",
        "eatin":"assets/images/public/eatin.png",
        "takeout":"assets/images/public/takeout.png",

      };
    }else if (shopInfo == 'sanfeng') {
      imagePack = {
        "backbutton_top":"assets/images/sanfeng/backbutton_top.png",
        "btn001":"assets/images/sanfeng/btn001.png",
        "btn002":"assets/images/sanfeng/btn002.png",
        "cargo_loading":"assets/images/public/cargo_loading.gif",
        "category_selected":"assets/images/sanfeng/category_selected.png",
        "category_unselected":"assets/images/sanfeng/category_unselected.png",
        "checked_green":"assets/images/sanfeng/checked_green.png",
        "delOne":"assets/images/sanfeng/delOne.png",
        "dialog_close":"assets/images/sanfeng/dialog_close.png",
        "home_button":"assets/images/sanfeng/home_button.png",
        "home":"assets/images/sanfeng/home.png",
        "load_error":"assets/images/sanfeng/load_error.png",
        "load_nodata":"assets/images/sanfeng/load_nodata.png",
        "logo":"assets/images/sanfeng/logo.png",
        "menu_up":"assets/images/sanfeng/menu_up.png",
        "optionChecked":"assets/images/sanfeng/optionChecked.png",
        "price_tag":"assets/images/sanfeng/price_tag.png",
        "price_subtraction_tag":"assets/images/sanfeng/price_subtraction_tag.png",
        "printticketloading":"assets/images/sanfeng/printticketloading.gif",
        "public_dingshi_option":"assets/images/sanfeng/public_dingshi_option.png",
        "public_dingshi_submit":"assets/images/sanfeng/public_dingshi_submit.png",
        "public_index_option":"assets/images/sanfeng/public_index_option.png",
        "public_index_submit":"assets/images/sanfeng/public_index_submit.png",
        "redDafen":"assets/images/sanfeng/redDafen.png",
        "redPutong":"assets/images/sanfeng/redPutong.png",
        "saoma":"assets/images/public/saoma.jpg",
        "settlement_alipay":"assets/images/sanfeng/settlement_alipay.png",
        "settlement_back":"assets/images/sanfeng/settlement_back.png",
        "settlement_cash":"assets/images/sanfeng/settlement_cash.png",
        "settlement_paypay":"assets/images/sanfeng/settlement_paypay.png",
        "settlement_tag":"assets/images/sanfeng/settlement_tag.png",
        "settlement_wechat":"assets/images/sanfeng/settlement_wechat.png",
        "shouqing_png":"assets/images/sanfeng/shouqing.png",
        "xianjin":"assets/images/public/xianjin.jpg",
        "eatin":"assets/images/public/eatin.png",
        "takeout":"assets/images/public/takeout.png",

      };
    }else if (shopInfo == 'rijindoujin') {
      imagePack = {
        "backbutton_top":"assets/images/rijindoujin/backbutton_top.png",
        "btn001":"assets/images/rijindoujin/btn001.png",
        "btn002":"assets/images/rijindoujin/btn002.png",
        "cargo_loading":"assets/images/public/cargo_loading.gif",
        "category_selected":"assets/images/rijindoujin/category_selected.png",
        "category_unselected":"assets/images/rijindoujin/category_unselected.png",
        "checked_green":"assets/images/rijindoujin/checked_green.png",
        "delOne":"assets/images/rijindoujin/delOne.png",
        "dialog_close":"assets/images/rijindoujin/dialog_close.png",
        "home_button":"assets/images/rijindoujin/home_button.png",
        "home":"assets/images/rijindoujin/home.png",
        "load_error":"assets/images/rijindoujin/load_error.png",
        "load_nodata":"assets/images/rijindoujin/load_nodata.png",
        "logo":"assets/images/rijindoujin/logo.png",
        "menu_up":"assets/images/rijindoujin/menu_up.png",
        "optionChecked":"assets/images/rijindoujin/optionChecked.png",
        "price_tag":"assets/images/rijindoujin/price_tag.png",
        "price_subtraction_tag":"assets/images/rijindoujin/price_subtraction_tag.png",
        "printticketloading":"assets/images/rijindoujin/printticketloading.gif",
        "public_dingshi_option":"assets/images/rijindoujin/public_dingshi_option.png",
        "public_dingshi_submit":"assets/images/rijindoujin/public_dingshi_submit.png",
        "public_index_option":"assets/images/rijindoujin/public_index_option.png",
        "public_index_submit":"assets/images/rijindoujin/public_index_submit.png",
        "redDafen":"assets/images/rijindoujin/redDafen.png",
        "redPutong":"assets/images/rijindoujin/redPutong.png",
        "saoma":"assets/images/public/saoma.jpg",
        "settlement_alipay":"assets/images/rijindoujin/settlement_alipay.png",
        "settlement_back":"assets/images/rijindoujin/settlement_back.png",
        "settlement_cash":"assets/images/rijindoujin/settlement_cash.png",
        "settlement_paypay":"assets/images/rijindoujin/settlement_paypay.png",
        "settlement_tag":"assets/images/rijindoujin/settlement_tag.png",
        "settlement_wechat":"assets/images/rijindoujin/settlement_wechat.png",
        "shouqing_png":"assets/images/rijindoujin/shouqing.png",
        "xianjin":"assets/images/public/xianjin.jpg",
        "eatin":"assets/images/public/eatin.png",
        "takeout":"assets/images/public/takeout.png",

      };
    }

    return imagePack[stringTag];
  }
}