const Map<String, String> en_US = {
//"top_back_button":"言語",
  //"top_back_button":"Home",
  "top_back_button":"Language",

  "show_price_front":"Tax-In",
  "tax_out":"Subtotal",
  "tax":"Incl. Tax",
  "out_tax":"Excl. Tax",
  "taxout_price":"Subtotal",
  "original_price":"Original Price",
  "show_original_price_front":"Orig",
  "settlement_button":"Check Out",
  "cancle_button":"Cancel all",
  "tag_title":"Reminder",
  "tag_content":"Are you sure you want to empty the shopping cart?",
  "tag_button_yes":"Yes",
  "tag_button_no":"No",
  "tag_checkOut":"Please scan QR code.",

  "menu_dingtype_eatin":"Eat-in",
  "menu_dingtype_takeout":"Takeout",
  "menu_dingtype_title":"Welcome",
  "menu_dingtype_title_tag":"Choose Eat-in or Takeout",
  "menu_dingtype_eatin_tag":"Click here for customers who eat in the store",
  "menu_dingtype_takeout_tag":"Click here for takeaway customers",
  "menu_ding_type_tips":"Please choose",

  "cart_tag":"Please select dishes",

  "add_option_cart":"Confirm",
  "settlement_total_price":"Total",
  "settlement_original_price":"Orig",
  "settlement_discount":"Discount",
  "settlement_small_ticket_tag":"We need a receipt, so please order us",
  //"settlement_payment_method":"Please select a payment method for your order：",
  "settlement_payment_method":"Please insert money or scan QR code.",
  "settlement_payment_method_only_cash":"Please insert money.",
  "settlement_payment_method_cash":"Cash",
  "settlement_payment_method_paypay":"PayPay",
  "settlement_payment_method_wechat":"WeChat Pay",
  "settlement_payment_method_alipay":"Alipay",
  "settlement_payment_method_study_cash":"Cash",
  "settlement_payment_method_study_qr":"QR Code Payments",
  "settlement_payment_method_title":"Guide to Payment Methods",
  "settlement_back":"Back",
  "settlement_back_alertcontent":"Do you want to cancel the payment?",
  "settlement_confirmButton":"Confirm",
  "settlement_confirmButton_yes":"Have a receipt",
  "settlement_confirmButton_no":"No receipt",
  "settlement_confirmButton_no2":"No receipt",
  "settlement_receipt_title":"Receipt",
  "settlement_receipt_yes":"Yes",
  "settlement_receipt_no":"No",
  "settlement_orderPrice":"Tatol amount",
  "settlement_putMoney":"Amount paid",
  "settlement_outMoney":"Change due",
  "settlement_print_outprice_tag":"Please take your change and receipt",
  "settlement_print_tag":"Please take your receipt.",
  "settlement_print_loading_tag":"Processing……",//, please wait
  "settlement_noprint_tag":"Please wait a moment.",
  "settlement_nopayment_error":"Payment failed, please choose another payment method.",
  "settlement_scancodenoopen_error":"Please select cash payment.",
  "settlement_scancodenochange_error":"Please choose another method。",
  "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
  "settlement_posPay_error_connect_worker":"Payment failed. Please contact the staff!",
  "settlement_posPay_connect_error":"The self-checkout is not connected to the terminal. Please ask the staff for assistance.",
  "settlement_posPay_loadint_title":"Payment processing. Please wait for a moment.",
  "settlement_posPay_tips_title":"Follow the instructions displayed on the terminal screen and proceed with the operation.",

  "tag_print_content_paper_shortage":"System error. Please contact our staff.",
  "tag_print_content_paper_error":"System error. Please contact our staff.",
  "tag_print_button_yes":"已处理",
  "tag_print_button_no":"不打印",
  "show_server_error":"System error. Please contact our staff.",
  //"show_put_money_error":"请继续投币",
  "show_please_select_error":"Please complete your order.",

  "settlement_top_title_cash":"Cash",
  "settlement_top_title_qr":"Code Payment",
  "settlement_top_title_card":"Credit Card",
  "settlement_top_title_wallet":"E-Wallet",
  "settlement_top_title_nfc":"Tap to pay",

  "settlement_top_title_edy":"楽天Edy",
  "settlement_top_title_iD":"iD",
  "settlement_top_title_IC":"IC",
  "settlement_top_title_QUICPay":"QUICPay",
  "settlement_top_title_WAON":"WAON",
  "settlement_top_title_nanaco":"nanaco",

  "select_payment_dining_title":"Please choose Eat in or Take out",
  "select_payment_type_title":"Please select a payment method",

  "payment_success_title":"Payment succeeded.",

  "show_storage_num_error":"Out of stock",

  "show_del_cart_item_tag":"Remove item？",
  "show_del_cart_item_yes":"Yes",
  "show_del_cart_item_no":"No",

  "show_product_restrictions":"LIMIT %%",
  "show_check_tableno":"Table No.",
  "select_checkOut_tip_title":"Choose in-store or takeout",
  "select_checkOut_tip_selected":"Check out",
  "checkoutScanTitle":"Bill",

  "menu_option_more_multipleState":"Up to %% maximum",
  "menu_option_less_smallest":"Please select %%",
  "show_selectPay_point":"",

  "select_selfservice_bag_title":"Would you like a bag?",
  "select_selfservice_nobag_title":"No",

  "cash_change_error_title":"Cash Payment",
  "cash_change_error_tips_up":"Cash payment machine failure, cash payment is not available.",
  "cash_change_error_tips_down":"Please switch to other payment methods or restart the application.",
  "reboot_app":"Restart",
  "change_payment":"Change payment method",

  "cancel_order":"Cancel order",
  "tag_out_money_error":"Insufficient change, please contact the staff",
  "error_tips_thanks":"Thank you for your operation. We have contacted the staff for processing. Please wait a moment.",
  "load_menu_failure_title" : "Menu loading error.",
  "load_menu_failure_content" : "Returning to the home screen in @seconds seconds, please try again.",
  "load_menu_failure_back" : "Back to home",
  'cash_pay_checkout_tips':'Payment amount updated, please continue inserting cash.',
  "scan_order_detail_title":"Order",

  "tag_amount":"Total",
  "tag_checkout":"Check Out",
  "order_start":"Order",

  "pos_report_error_tips":"Payment failed. Please contact the staff!",
  "pay_success_title":"Payment Successful\nThank you for your use",

  "tag_cash_error":"Cash machine error, please contact the staff, thank you!",
  "show_order_error":"Order failed, please try again.",
  "order_network_error":"Network error, please contact the staff.",
  "settlement_order_error":"Payment failed, please try again.",

  "cancel_button" : "Cancel",
  "retry_button" : "Retry",
  "status_check" : "Status Check",
  "status_check_tips" : "Checking printer status...",
  "status_on" : "On",
  "status_off" : "Off",
  "go_setting" : "Go to Settings",

  "settlement_posnosetting_error":"POS machine is not set. Please contact the staff. Thank you!",
  "pos_check_title": "POS machine status check",
  "pos_checking": "Checking POS machine status, please confirm whether the POS machine status is normal. If the POS machine is abnormal, the check process will automatically end after 2 minutes.",
  "pos_check_success": "POS machine status is normal.",
  "pos_check_failed": "POS machine status is abnormal.",

  "skip_button":"Skip",
  "next_button":"Next",
  "suggest_title":"You may also like",

  "order_success_title":"Payment Successful",
  "order_success_tips":"Thank you for your order.",
  "order_success_subtips":"Returning to the home screen in %% seconds.",
  "origin_home":"Back to Home",

  "settlement_unexpected_error" : "Payment exception occurred. Please return to the previous page and try again.",
  "pos_cancel_wait_tips": "Transaction in progress, cannot cancel at the moment, please wait. Maximum wait time is 2 minutes.",
  "voucher_amount":"Voucher Discount",

  "tag_scan_network_error":"Order request failed, please try again later.",
  "tag_scan_network_timeout":"Order request timed out, please try again later.",

  "menu_spicy_hot_pot":"Spicy Hot Pot",

  // Spicy hot pot weigh / soup options
  "spicy_step_start":"Start",
  "spicy_step_weigh":"Weigh",
  "spicy_step_soup":"Soup",
  "spicy_step_topping":"Toppings",
  "spicy_step_checkout":"Checkout",
  "spicy_step_pay":"Pay",
  "spicy_weigh_title":"Please weigh your bowl",
  "spicy_weigh_subtitle":"Place the bowl on the scale",
  "spicy_weigh_unit_price":"Unit price",
  "spicy_weigh_remeasure":"Weigh again",
  "spicy_weigh_scale_disconnected":"Scale not connected",
  "spicy_weigh_stable":"Weight is stable",
  "spicy_weigh_settling":"Weighing… please wait until stable",
  "spicy_weigh_container_tip":"Container weight will be deducted at checkout",
  "spicy_weigh_skip":"Skip weighing",
  "spicy_weigh_waiting_stable":"Waiting…",
  "spicy_soup_title":"Choose your soup base",
  "spicy_soup_subtitle":"Tap the soup you prefer",
  "spicy_soup_no_extra_option":"No extra options for this item",
  "spicy_soup_select_options":"Select options",
  "spicy_soup_options_for":"Select options for @name",
  "spicy_soup_recommend":"Recommended",
  "spicy_weigh_manual_allow_title":"Manual input settings",
  "spicy_weigh_manual_allow":"Allow manual weight input",
  "spicy_weigh_manual_input":"Manual input",
  "spicy_weigh_manual_input_title":"Enter weight (g)",
  "spicy_weigh_manual_ready":"Manual weight entered (you can continue)",
  "spicy_mode_preparing":"Preparing the scale…",

  "spicy_menu_scan_title":"Scan barcode to add to cart",
  "spicy_menu_scan_subtitle":"Or tap a product directly",
  "spicy_menu_scan_howto":"How to use",
  "spicy_menu_scan_howto_title":"How to use barcode",
  "spicy_menu_scan_howto_body":"Scan the barcode and the item will be added to your cart automatically",
};
