const Map<String, String> ja_JP = {
  //"top_back_button":"言語",
  //"top_back_button":"ホーム",
  "top_back_button":"Language",

  "show_price_front":"税込",
  "tax_out":"税抜",
  "tax":"内 消費税",
  "out_tax":"外　消費税",
  "taxout_price":"小計",
  "original_price":"原価",
  "show_original_price_front":"定価",
  "settlement_button":"お会計",
  "cancle_button":"すべてキャンセル",
  "tag_title":"お知らせ",
  "tag_content":"ショッピングカートを空にします?",
  "tag_button_yes":"はい",
  "tag_button_no":"いいえ",
  "tag_checkOut":"QRコードをスキャンしてください",

  "menu_dingtype_eatin":"店内",
  "menu_dingtype_takeout":"お持ち帰り",
  "menu_dingtype_title":"いらっしゃいませ",
  "menu_dingtype_title_tag":"店内またはテイクアウトをお選びください",
  "menu_dingtype_eatin_tag":"店内でお召し上がりのお客様はこちら",
  "menu_dingtype_takeout_tag":"テイクアウトのお客様はこちら",
  "menu_ding_type_tips":"いずれかお選びください",

  "cart_tag":"メニューをお選びください",

  "add_option_cart":"確  認",
  "settlement_total_price":"合計",
  "settlement_original_price":"定価",
  "settlement_discount":"割引",
  "settlement_small_ticket_tag":"領収書が必要ですのでこちらをご注文ください",
  //"settlement_payment_method":"以下のお支払い方法をご利用いただけます。",
  "settlement_payment_method":"現金を投入するか、QRコードをスキャンしてください。",
  "settlement_payment_method_only_cash":"現金を投入してください。",
  "settlement_payment_method_cash":"Cash",
  "settlement_payment_method_paypay":"PayPay",
  "settlement_payment_method_wechat":"WeChat Pay",
  "settlement_payment_method_alipay":"Alipay",
  "settlement_payment_method_study_cash":"現金",
  "settlement_payment_method_study_qr":"QRコード決済",
  "settlement_payment_method_title":"お支払い方法のガイド",
  "settlement_back":"戻る",
  "settlement_back_alertcontent":"お支払いを取り消ししますか？",
  "settlement_confirmButton":"支払い確定",
  "settlement_confirmButton_yes":"領収書発行",
  "settlement_confirmButton_no2":"支払い確定",
  "settlement_confirmButton_no":"領収書不発行",
  "settlement_receipt_title":"領収書",
  "settlement_receipt_yes":"発行する",
  "settlement_receipt_no":"発行しない",
  "settlement_orderPrice":"お支払い金額",
  "settlement_putMoney":"お預り    ",
  "settlement_outMoney":"お釣り    ",
  "settlement_print_outprice_tag":"    お釣りを取って下さい  \r\n しばらくお待ちください",
  "settlement_print_tag":"しばらくお待ちください",
  "settlement_print_loading_tag":"しばらくお待ちください",//少々お待ちください
  "settlement_noprint_tag":"しばらくお待ちください",
  "settlement_nopayment_error":"        支払いが失敗しました。  \r\n 他の支払い方法をお選ぶください。",
  "settlement_scancodenoopen_error":" 済みません、今度は現金でお願いします。",
  "settlement_scancodenochange_error":"済みません、他の支払い方法を選んでください。",
  "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
  "settlement_posPay_error_connect_worker":"支払いが失敗しました。\r\n 他の支払い方法をお選ぶください。",//スタッフに連絡してください！
  "settlement_posPay_connect_error":"セルフレジは端末に接続されてません、スタフに聞いてお願いします。",
  "settlement_posPay_loadint_title":"支払処理中です、しばらくお待ち下さい。",
  "settlement_posPay_tips_title":"端末の画面に表示される指示に従って、操作してください。",

  "tag_print_content_paper_shortage":"用紙切れです、お近くのスタッフにお知らせください",
  "tag_print_content_paper_error":"故障、お近くのスタッフにお知らせください",
  "tag_print_button_yes":"処理済み",
  "tag_print_button_no":"印刷しない",

  "show_server_error":"しばらく経ってから、やり直してください",
  //"show_put_money_error":"続けてコインを入れてください",
  "show_please_select_error":"メニューをお選びください",

  "settlement_top_title_cash":"現金",
  "settlement_top_title_qr":"バーコード決済",
  "settlement_top_title_card":"クレジットカード",
  "settlement_top_title_wallet":"電子マネー",
  "settlement_top_title_nfc":"タッチ決済",

  "settlement_top_title_edy":"楽天Edy",
  "settlement_top_title_iD":"iD",
  "settlement_top_title_IC":"IC",
  "settlement_top_title_QUICPay":"QUICPay",
  "settlement_top_title_WAON":"WAON",
  "settlement_top_title_nanaco":"nanaco",

  "select_payment_dining_title":"店内または持ち帰りをお選びください",
  "select_payment_type_title":"支払い方法をお選びください",

  "payment_success_title":"支払完了いたしました",

  "show_storage_num_error":"この料理の在庫が不足しています",

  "show_del_cart_item_tag":"商品を削除しますか?",
  "show_del_cart_item_yes":"はい",
  "show_del_cart_item_no":"いいえ",

  "show_product_restrictions":"数量限定",//"""%%份限定",
  "show_check_tableno":"お席番号：",

  "select_checkOut_tip_title":"店内またはテイクアウトをお選びください",
  "select_checkOut_tip_selected":"                店内      \r\n（お食事後のお会計）",
  "checkoutScanTitle":"お会計",

  "menu_option_more_multipleState":"最大%%にまで",
  "menu_option_less_smallest":"%%をお選びください",
  "show_selectPay_point":"点",

  "select_selfservice_bag_title":"请选择是否需要袋子",
  "select_selfservice_nobag_title":"不要",

  "cash_change_error_title":"現金払い",
  "cash_change_error_tips_up":"現在、現金機に通障害が発生しており、現金でのお支払いはご利用いただけません。",
  "cash_change_error_tips_down":"キャッシュレスの支払い方法に変更するか、アプリを再起動してみてください。",
  "reboot_app":"再起動",
  "change_payment":"支払い方法を変更",

  "cancel_order":"注文をキャンセル",
  "tag_out_money_error":"お釣りが足りません,お近くのスタッフにお知らせください",
  "error_tips_thanks":"操作ありがとうございます。処理のために店舗スタッフに連絡しました。しばらくお待ちください。",

  "load_menu_failure_title" : "メニューの読み込みに異常が発生しました。",
  "load_menu_failure_content" : "@seconds秒後にホーム画面に戻りますので、\n再度お試しください。",
  "load_menu_failure_back" : "ホームに戻る",
  'cash_pay_checkout_tips':'支払い金額が更新されました。引き続き現金を投入してください。',
  "scan_order_detail_title":"ご注文",

  "tag_amount":"合計",
  "tag_checkout":"お会計",
  "order_start":"注文",

  "pos_report_error_tips":"申し訳ございません、決済失敗ので、店員に対応を依頼してください。",
  "pay_success_title":"お支払いが成功しました\nご利用いただきありがとうございます",

  "tag_cash_error":"現金機に障害が発生しております、店員にお知らせください。",
  "show_order_error":"注文に失敗しました、もう一度お試しください。",
  "order_network_error":"ネットワークエラー、店員にお知らせください。",
  "settlement_order_error":"決済失敗ので、もう一度お試しください。",
  "cancel_button" : "キャンセル",
  "retry_button" : "再試行",
  "status_check" : "ステータスチェック",
  "status_check_tips" : "プリンターのステータスを確認しています...",
  "status_on" : "オンです",
  "status_off" : "オフです",
  "go_setting" : "設定へ",

  "settlement_posnosetting_error":"POS端末が設定されていません。スタッフに連絡してください。ありがとうございます！",
  "pos_check_title": "POS端末の状態チェック",
  "pos_checking": "POS端末の状態を確認中です。POS端末の状態が正常かどうかをご確認ください。POS端末に異常がある場合、チェックプロセスは2分後に自動的に終了します。",
  "pos_check_success": "POS端末の状態は正常です。",
  "pos_check_failed": "POS端末の状態は異常です。",

  "skip_button":"スキップ",
  "next_button":"進む",
  "suggest_title":"ご一緒にいかがですか",
  "pos_cancel_wait_tips": "取引中のため、キャンセルできません。しばらくお待ちください。最大待機時間は2分です。",

  "settlement_unexpected_error" : "決済中に予期しないエラーが発生しました。前のページに戻って再試行してください。",

  "order_success_title":"支払い完了",
  "order_success_tips":"ご利用いただきありがとうございました",
  "order_success_subtips":"%%秒後に自動で最初の画面に戻ります",
  "origin_home":"最初の画面に戻る",
  "voucher_amount":"代金券・売掛",

  "tag_scan_network_error": "注文リクエストに失敗しました。後でもう一度お試しください。",
  "tag_scan_network_timeout": "注文リクエストがタイムアウトしました。後でもう一度お試しください。",
};