const Map<String, String> ja_JP = {
        //"top_back_button":"言語",
        //"top_back_button":"ホーム",
        "top_back_button":"Language",

        "show_price_front":"税込",
        "tax_out":"小計",
        "tax":"消費税",
        "taxout_price":"小計",
        "original_price":"原価",
        "show_original_price_front":"定価",
        "settlement_button":"お会計",
        "cancle_button":"すべてキャンセル",
        "tag_title":"お知らせ",
        "tag_content":"ショッピングカートを空にします?",
        "tag_button_yes":"はい",
        "tag_button_no":"いいえ",
        "tag_checkOut":"QRコードをスキャンしてください",

        "menu_dingtype_eatin":"店内",
        "menu_dingtype_takeout":"テイクアウト",
        "menu_dingtype_title":"いらっしゃいませ",
        "menu_dingtype_title_tag":"店内またはテイクアウトをお選びください",
        "menu_dingtype_eatin_tag":"店内でお召し上がりのお客様はこちら",
        "menu_dingtype_takeout_tag":"テイクアウトのお客様はこちら",
        "menu_ding_type_tips":"いずれかお選びください",

        "cart_tag":"メニューをお選びください",

        "add_option_cart":"確  認",
        "settlement_total_price":"合計",
        "settlement_original_price":"定価",
        "settlement_discount":"割引",
        "settlement_small_ticket_tag":"領収書が必要ですのでこちらをご注文ください",
        //"settlement_payment_method":"以下のお支払い方法をご利用いただけます。",
        "settlement_payment_method":"現金を投入するか、QRコードをスキャンしてください。",
        "settlement_payment_method_only_cash":"現金を投入してください。",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"現金",
        "settlement_payment_method_study_qr":"QRコード決済",
        "settlement_payment_method_title":"お支払い方法のガイド",
        "settlement_back":"戻る",
        "settlement_back_alertcontent":"お支払いを取り消ししますか？",
        "settlement_confirmButton":"支払い確定",
        "settlement_confirmButton_yes":"領収書発行",
        "settlement_confirmButton_no2":"支払い確定",
        "settlement_confirmButton_no":"領収書不発行",
        "settlement_receipt_title":"領収書",
        "settlement_receipt_yes":"発行する",
        "settlement_receipt_no":"発行しない",
        "settlement_orderPrice":"お支払い金額",
        "settlement_putMoney":"お預り    ",
        "settlement_outMoney":"お釣り    ",
        "settlement_print_outprice_tag":"    お釣りを取って下さい  \r\n しばらくお待ちください",
        "settlement_print_tag":"しばらくお待ちください",
        "settlement_print_loading_tag":"しばらくお待ちください",//少々お待ちください
        "settlement_noprint_tag":"しばらくお待ちください",
        "settlement_nopayment_error":"        支払いが失敗しました。  \r\n 他の支払い方法をお選ぶください。",
        "settlement_scancodenoopen_error":" 済みません、今度は現金でお願いします。",
        "settlement_scancodenochange_error":"済みません、他の支払い方法を選んでください。",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_error_connect_worker":"支払いが失敗しました。\r\n 他の支払い方法をお選ぶください。",//スタッフに連絡してください！
        "settlement_posPay_connect_error":"セルフレジは端末に接続されてません、スタフに聞いてお願いします。",
        "settlement_posPay_loadint_title":"支払処理中です、しばらくお待ち下さい。",
        "settlement_posPay_tips_title":"端末の画面に表示される指示に従って、操作してください。",

        "tag_print_content_paper_shortage":"用紙切れです、お近くのスタッフにお知らせください",
        "tag_print_content_paper_error":"故障、お近くのスタッフにお知らせください",
        "tag_print_button_yes":"処理済み",
        "tag_print_button_no":"印刷しない",

        "show_server_error":"しばらく経ってから、やり直してください",
        //"show_put_money_error":"続けてコインを入れてください",
        "show_please_select_error":"メニューをお選びください",

        "settlement_top_title_cash":"現金",
        "settlement_top_title_qr":"バーコード決済",
        "settlement_top_title_card":"クレジットカード",
        "settlement_top_title_wallet":"電子マネー",
        "settlement_top_title_nfc":"タッチ決済",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"店内または持ち帰りをお選びください",
        "select_payment_type_title":"支払い方法をお選びください",

        "payment_success_title":"支払完了いたしました",

        "show_storage_num_error":"この料理の在庫が不足しています",

        "show_del_cart_item_tag":"商品を削除しますか?",
        "show_del_cart_item_yes":"はい",
        "show_del_cart_item_no":"いいえ",

        "show_product_restrictions":"数量限定",//"""%%份限定",
        "show_check_tableno":"お席番号：",

        "select_checkOut_tip_title":"店内またはテイクアウトをお選びください",
        "select_checkOut_tip_selected":"                店内      \r\n（お食事後のお会計）",
        "checkoutScanTitle":"お会計",

        "menu_option_more_multipleState":"最大%%にまで",
        "menu_option_less_smallest":"%%をお選びください",
        "show_selectPay_point":"点",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"現金払い",
        "cash_change_error_tips_up":"現在、現金機に通障害が発生しており、現金でのお支払いはご利用いただけません。",
        "cash_change_error_tips_down":"キャッシュレスの支払い方法に変更するか、アプリを再起動してみてください。",
        "reboot_app":"再起動",
        "change_payment":"支払い方法を変更",

        "cancel_order":"注文をキャンセル",
        "tag_out_money_error":"お釣りが足りません,お近くのスタッフにお知らせください",
        "error_tips_thanks":"操作ありがとうございます。処理のために店舗スタッフに連絡しました。しばらくお待ちください。",

        "load_menu_failure_title" : "メニューの読み込みに異常が発生しました。",
        "load_menu_failure_content" : "@seconds秒後にホーム画面に戻りますので、\n再度お試しください。",
        "load_menu_failure_back" : "ホームに戻る",
        'cash_pay_checkout_tips':'支払い金額が更新されました。引き続き現金を投入してください。',
        "scan_order_detail_title":"ご注文",

        "tag_amount":"合計",
        "tag_checkout":"お会計",
        "order_start":"注文",
        "take_out":"持ち帰り",
        "pos_report_error_tips":"申し訳ございません、決済失敗ので、店員に対応を依頼してください。",
        "pay_success_title":"お支払いが成功しました\nご利用いただきありがとうございます",

        "tag_cash_error":"現金機に障害が発生しております、店員にお知らせください。",
        "show_order_error":"注文に失敗しました、もう一度お試しください。",
        "order_network_error":"ネットワークエラー、店員にお知らせください。",
        "settlement_order_error":"決済失敗ので、もう一度お試しください。",

        "checkoutScanTips": "QRコードをスキャンボックスに置いてください",
        "cancel_button" : "キャンセル",
        "retry_button" : "再試行",
        "status_check" : "ステータスチェック",
        "status_check_tips" : "プリンターのステータスを確認しています...",
        "status_on" : "オンです",
        "status_off" : "オフです",
        "go_setting" : "設定へ",

        "payment_cash_unavailable" : "現金はご利用いただけません、他の支払い方法を選択してください。",
        "activation_error_tips" : "アクティベーションコードが間違っています。再度入力してください。",

                //Error handle message
        "cash_error_no_hardware": "現金機が接続されていません。スタッフに連絡してください。", 
        "cash_error_busy": "処理中です。しばらくしてから再試行してください。", 
        "cash_error_no_service": "サービスは利用できません。スタッフに連絡してください。", 
        "cash_error_illegal": "すでに開いています。再度開かないでください。", 
        "cash_error_no_claimed": "サービスは利用できません。スタッフに連絡してください。",
        "cash_error_disabled": "デバイスが無効になっています。スタッフに連絡してください。", 
        "cash_error_claimed": "サービスは利用できません。スタッフに連絡してください。", 
        "cash_error_closed": "サービスは利用できません。スタッフに連絡してください。",
        "cash_error_common": "エラーが発生しました。スタッフに連絡してください。", 
        "cash_error_over_dispense": "お釣り金額が最大限度を超えています。注文をキャンセルし、店舗に連絡してください。", 
        "cash_error_over": "お釣り金額が設定金額を超えています。注文をキャンセルし、店舗に連絡してください。", 
        "cash_error_if_error": "通信エラーが発生しました。再試行してください。", 
        "cash_error_set_error": "オフライン状態です。店舗に連絡してください。", 
        "cash_error_charging": "お釣りを計算中です。しばらくお待ちください。",
        "cash_error_full": "お釣り箱が満杯です。店舗に連絡してください。", 
        "cash_error_cassette_wait": "お釣りを取り出してください。",
        "cash_error_impossible": "現在の状態では操作を実行できません。店舗に連絡してください。", 
        "cash_error_deposit": "カウント中です。しばらくお待ちください。", 
        "cash_error_pause_deposit": "カウントが一時停止しています。店舗に連絡してください。", 
        "cash_error_open": "オープンエラーが発生しました。スタッフに連絡してください。", 
        "cash_error_reg_bad_name": "デバイス名が間違っています。デバイス設定を確認してください。", 
        "cash_error_reg_prog_id": "プログラムIDが間違っています。デバイス設定を確認してください。", 
        "cash_error_create": "デバイスの作成に失敗しました。デバイス設定を確認してください。", 
        "cash_error_bad_if": "インターフェースエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_no_port": "ポートが見つかりません。デバイス設定を確認してください。", 
        "cash_error_sense_thread": "センサースレッドが見つかりません。デバイス設定を確認してください。", 
        "cash_error_config": "設定エラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_event_thread": "イベントスレッドが見つかりません。デバイス設定を確認してください。", 
        "cash_error_failed_open": "オープンに失敗しました。デバイス設定を確認してください。", 
        "cash_error_event_class": "イベントクラスが見つかりません。デバイス設定を確認してください。", 
        "cash_error_bad_version": "バージョンエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_open_so": "SOファイルが見つかりません。デバイス設定を確認してください。", 
        "cash_error_no_ported": "ポートが見つかりません。デバイス設定を確認してください。", 
        "cash_error_specific": "特定のエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_unknown": "不明なエラーが発生しました。デバイス設定を確認してください。",


        "in_shop":"店内",
        "more_title":"もっと見る",
        "main_page":"ホーム",

        //"scan_order_detail_title":"ご注文",
        "dining_welcome":"いらっしゃいませ",
        "dining_type_tips":"店内かお持ち帰りかを選択してください",
        "checkout_type_tips":"お会計かお持ち帰りかを選択してください",
        "amount_tips":"'お会計'をターチしてください",
        //'cash_pay_checkout_tips':'お支払い金額の変更あり、改めて金額のご確認し、お支払いください。',
        'cash_full_confirm':'確定',
        'cash_full_tips':'金種@cash が上限に達しました。「確定」をクリックすると入金が返金されます。他の金種や支払い方法をご利用いただくか、店舗にお問い合わせください。ご不便をおかけして申し訳ございません。',
        "skip_button":"スキップ",
        "next_button":"進む",
        "suggest_title":"ご一緒にいかがですか",

        "repay_cash_error": "エラーが発生しました, スタッフに連絡してください。",
        "network_error_tips":"申し訳ございません。ネットワークの異常により、一時的にご利用いただけません。店員にお問い合わせいただくか、取引をキャンセルしてください。",
        "pos_notwork_tips":"申し訳ございません。POS端末が応答しません。店員に対応を依頼してください。ありがとうございます。",

};