const Map<String, String> vi_VN = {
  'top_back_button': 'Ngôn ngữ',
  'show_price_front': 'Đã bao gồm thuế',
  'tax_out': 'Tạm tính',
  'tax': 'Thuế đã bao gồm',
  'out_tax': 'Chưa bao gồm thuế',
  'taxout_price': 'Tạm tính',
  'original_price': 'Giá gốc',
  'show_original_price_front': 'Giá gốc',
  'settlement_button': 'Thanh toán',
  'cancle_button': 'Hủy tất cả',
  'tag_title': 'Thông báo',
  'tag_content': 'Bạn có chắc muốn xóa giỏ hàng không?',
  'tag_button_yes': 'Có',
  'tag_button_no': 'Không',
  'tag_checkOut': 'Vui lòng quét mã QR.',
  'menu_dingtype_eatin': 'Dùng tại quán',
  'menu_dingtype_takeout': 'Mang đi',
  'menu_dingtype_title': 'Xin chào',
  'menu_dingtype_title_tag': 'Chọn dùng tại quán hoặc mang đi',
  'menu_dingtype_eatin_tag': 'Nhấn vào đây để dùng tại quán',
  'menu_dingtype_takeout_tag': 'Nhấn vào đây để mang đi',
  'menu_ding_type_tips': 'Vui lòng chọn',
  'cart_tag': 'Vui lòng chọn món',
  'add_option_cart': 'Xác nhận',
  'settlement_total_price': 'Tổng cộng',
  'settlement_original_price': 'Giá gốc',
  'settlement_discount': 'Giảm giá',
  'settlement_small_ticket_tag': 'Vui lòng xác nhận in hóa đơn',
  'settlement_payment_method': 'Vui lòng cho tiền vào hoặc quét mã QR.',
  'settlement_payment_method_only_cash': 'Vui lòng cho tiền vào.',
  'settlement_payment_method_cash': 'Tiền mặt',
  'settlement_payment_method_paypay': 'PayPay',
  'settlement_payment_method_wechat': 'WeChat Pay',
  'settlement_payment_method_alipay': 'Alipay',
  'settlement_payment_method_study_cash': 'Tiền mặt',
  'settlement_payment_method_study_qr': 'Thanh toán mã QR',
  'settlement_payment_method_title': 'Hướng dẫn phương thức thanh toán',
  'settlement_back': 'Quay lại',
  'settlement_back_alertcontent': 'Bạn có muốn hủy thanh toán không?',
  'settlement_confirmButton': 'Xác nhận thanh toán',
  'settlement_confirmButton_yes': 'In hóa đơn',
  'settlement_confirmButton_no': 'Không in hóa đơn',
  'settlement_confirmButton_no2': 'Không in hóa đơn',
  'settlement_receipt_title': 'Hóa đơn',
  'settlement_receipt_yes': 'Có',
  'settlement_receipt_no': 'Không',
  'settlement_orderPrice': 'Số tiền thanh toán',
  'settlement_putMoney': 'Số tiền đã nhận',
  'settlement_outMoney': 'Tiền thối',
  'settlement_print_outprice_tag': 'Vui lòng nhận tiền thối và hóa đơn',
  'settlement_print_tag': 'Vui lòng nhận hóa đơn.',
  'settlement_print_loading_tag': 'Đang xử lý…',
  'settlement_noprint_tag': 'Vui lòng chờ trong giây lát.',
  'settlement_nopayment_error':
      'Thanh toán thất bại. Vui lòng chọn phương thức khác.',
  'settlement_scancodenoopen_error': 'Vui lòng chọn thanh toán bằng tiền mặt.',
  'settlement_scancodenochange_error':
      'Vui lòng chọn phương thức thanh toán khác.',
  'settlement_posPay_error':
      'Thanh toán thất bại. Vui lòng chọn phương thức khác.',
  'settlement_posPay_error_connect_worker':
      'Thanh toán thất bại. Vui lòng liên hệ nhân viên!',
  'settlement_posPay_connect_error':
      'Máy tự thanh toán chưa kết nối với thiết bị. Vui lòng liên hệ nhân viên.',
  'settlement_posPay_loadint_title': 'Đang xử lý thanh toán. Vui lòng chờ.',
  'settlement_posPay_tips_title':
      'Vui lòng làm theo hướng dẫn trên màn hình thiết bị.',
  'tag_print_content_paper_shortage':
      'Máy in hết giấy. Vui lòng liên hệ nhân viên.',
  'tag_print_content_paper_error': 'Lỗi in. Vui lòng liên hệ nhân viên.',
  'tag_print_button_yes': 'Đã xử lý',
  'tag_print_button_no': 'Không in',
  'show_server_error': 'Lỗi hệ thống. Vui lòng thử lại sau.',
  'show_please_select_error': 'Vui lòng chọn món.',
  'settlement_top_title_cash': 'Tiền mặt',
  'settlement_top_title_qr': 'Thanh toán mã QR',
  'settlement_top_title_card': 'Thẻ tín dụng',
  'settlement_top_title_wallet': 'Ví điện tử',
  'settlement_top_title_nfc': 'Thanh toán chạm',
  'settlement_top_title_edy': 'Rakuten Edy',
  'settlement_top_title_iD': 'iD',
  'settlement_top_title_IC': 'IC',
  'settlement_top_title_QUICPay': 'QUICPay',
  'settlement_top_title_WAON': 'WAON',
  'settlement_top_title_nanaco': 'nanaco',
  'select_payment_dining_title': 'Vui lòng chọn dùng tại quán hoặc mang đi',
  'select_payment_type_title': 'Vui lòng chọn phương thức thanh toán',
  'payment_success_title': 'Thanh toán thành công.',
  'show_storage_num_error': 'Món này đã hết hàng',
  'show_del_cart_item_tag': 'Bạn có muốn xóa món này không?',
  'show_del_cart_item_yes': 'Xóa',
  'show_del_cart_item_no': 'Không xóa',
  'show_product_restrictions': 'Giới hạn %%',
  'show_check_tableno': 'Số bàn',
  'select_checkOut_tip_title': 'Chọn thanh toán hoặc mang đi',
  'select_checkOut_tip_selected': 'Thanh toán',
  'checkoutScanTitle': 'Thanh toán',
  'menu_option_more_multipleState': 'Tối đa %%',
  'menu_option_less_smallest': 'Vui lòng chọn %%',
  'show_selectPay_point': 'món',
  'select_selfservice_bag_title': 'Bạn có cần túi không?',
  'select_selfservice_nobag_title': 'Không cần',
  'cash_change_error_title': 'Thanh toán bằng tiền mặt',
  'cash_change_error_tips_up':
      'Máy thanh toán tiền mặt đang gặp sự cố nên không thể sử dụng.',
  'cash_change_error_tips_down':
      'Vui lòng chọn phương thức khác hoặc khởi động lại ứng dụng.',
  'reboot_app': 'Khởi động lại',
  'change_payment': 'Đổi phương thức thanh toán',
  'cancel_order': 'Hủy đơn hàng',
  'tag_out_money_error': 'Không đủ tiền thối. Vui lòng liên hệ nhân viên.',
  'error_tips_thanks':
      'Cảm ơn bạn. Chúng tôi đã thông báo cho nhân viên, vui lòng chờ.',
  'load_menu_failure_title': 'Không thể tải thực đơn.',
  'load_menu_failure_content':
      'Sẽ quay lại màn hình chính sau @seconds giây. Vui lòng thử lại.',
  'load_menu_failure_back': 'Về trang chính',
  'cash_pay_checkout_tips':
      'Số tiền thanh toán đã thay đổi. Vui lòng tiếp tục cho tiền vào.',
  'scan_order_detail_title': 'Đơn hàng',
  'tag_amount': 'Tổng cộng',
  'tag_checkout': 'Thanh toán',
  'order_start': 'Đặt món',
  'take_out': 'Mang đi',
  'pos_report_error_tips': 'Thanh toán thất bại. Vui lòng liên hệ nhân viên!',
  'pay_success_title': 'Thanh toán thành công\nCảm ơn quý khách',
  'tag_cash_error': 'Máy tiền mặt gặp sự cố. Vui lòng liên hệ nhân viên.',
  'show_order_error': 'Đặt hàng thất bại. Vui lòng thử lại.',
  'order_network_error': 'Lỗi mạng. Vui lòng liên hệ nhân viên.',
  'settlement_order_error': 'Thanh toán thất bại. Vui lòng thử lại.',
  'checkoutScanTips': 'Vui lòng đặt mã QR vào vùng quét',
  'cancel_button': 'Hủy',
  'retry_button': 'Thử lại',
  'status_check': 'Kiểm tra trạng thái',
  'status_check_tips': 'Đang kiểm tra trạng thái máy in…',
  'status_on': 'Bật',
  'status_off': 'Tắt',
  'go_setting': 'Đến cài đặt',
  'payment_cash_unavailable':
      'Không thể thanh toán bằng tiền mặt. Vui lòng chọn phương thức khác.',
  'activation_error_tips': 'Mã kích hoạt không chính xác. Vui lòng nhập lại.',
  'cash_error_no_hardware':
      'Máy tiền mặt chưa được kết nối. Vui lòng liên hệ nhân viên.',
  'cash_error_busy': 'Đang xử lý. Vui lòng chờ.',
  'cash_error_no_service':
      'Dịch vụ không khả dụng. Vui lòng liên hệ nhân viên.',
  'cash_error_illegal': 'Thiết bị đã mở. Vui lòng liên hệ nhân viên.',
  'cash_error_no_claimed':
      'Dịch vụ không khả dụng. Vui lòng liên hệ nhân viên.',
  'cash_error_disabled':
      'Thiết bị đã bị vô hiệu hóa. Vui lòng liên hệ nhân viên.',
  'cash_error_claimed': 'Dịch vụ không khả dụng. Vui lòng liên hệ nhân viên.',
  'cash_error_closed': 'Dịch vụ không khả dụng. Vui lòng liên hệ nhân viên.',
  'cash_error_common': 'Đã xảy ra lỗi. Vui lòng liên hệ nhân viên.',
  'cash_error_over_dispense':
      'Tiền thối vượt quá giới hạn. Vui lòng hủy đơn và liên hệ cửa hàng.',
  'cash_error_over':
      'Tiền thối vượt quá số tiền đã cài đặt. Vui lòng hủy đơn và liên hệ cửa hàng.',
  'cash_error_if_error': 'Đã xảy ra lỗi giao tiếp. Vui lòng thử lại.',
  'cash_error_set_error':
      'Thiết bị đang ngoại tuyến. Vui lòng liên hệ nhân viên.',
  'cash_error_charging': 'Đang tính tiền thối. Vui lòng chờ.',
  'cash_error_full': 'Hộp tiền thối đã đầy. Vui lòng liên hệ cửa hàng.',
  'cash_error_cassette_wait': 'Vui lòng nhận tiền thối.',
  'cash_error_impossible':
      'Không thể thực hiện thao tác này. Vui lòng liên hệ nhân viên.',
  'cash_error_deposit': 'Đang đếm tiền. Vui lòng chờ.',
  'cash_error_pause_deposit':
      'Việc đếm tiền đã tạm dừng. Vui lòng liên hệ nhân viên.',
  'cash_error_open': 'Lỗi mở thiết bị. Vui lòng liên hệ nhân viên.',
  'cash_error_reg_bad_name':
      'Tên thiết bị không chính xác. Vui lòng kiểm tra cài đặt.',
  'cash_error_reg_prog_id':
      'ID chương trình không chính xác. Vui lòng kiểm tra cài đặt.',
  'cash_error_create': 'Không thể tạo thiết bị. Vui lòng kiểm tra cài đặt.',
  'cash_error_bad_if': 'Lỗi giao diện. Vui lòng kiểm tra cài đặt.',
  'cash_error_no_port':
      'Không tìm thấy cổng kết nối. Vui lòng kiểm tra cài đặt.',
  'cash_error_sense_thread':
      'Không tìm thấy luồng cảm biến. Vui lòng kiểm tra cài đặt.',
  'cash_error_config': 'Lỗi cấu hình. Vui lòng kiểm tra cài đặt.',
  'cash_error_event_thread':
      'Không tìm thấy luồng sự kiện. Vui lòng kiểm tra cài đặt.',
  'cash_error_failed_open': 'Không thể mở thiết bị. Vui lòng kiểm tra cài đặt.',
  'cash_error_event_class':
      'Không tìm thấy lớp sự kiện. Vui lòng kiểm tra cài đặt.',
  'cash_error_bad_version':
      'Phiên bản không phù hợp. Vui lòng kiểm tra cài đặt.',
  'cash_error_open_so': 'Không tìm thấy tệp SO. Vui lòng kiểm tra cài đặt.',
  'cash_error_no_ported':
      'Không tìm thấy cổng kết nối. Vui lòng kiểm tra cài đặt.',
  'cash_error_specific': 'Đã xảy ra lỗi thiết bị. Vui lòng kiểm tra cài đặt.',
  'cash_error_unknown':
      'Đã xảy ra lỗi không xác định. Vui lòng kiểm tra cài đặt.',
  'in_shop': 'Dùng tại quán',
  'more_title': 'Xem thêm',
  'main_page': 'Trang chính',
  'dining_welcome': 'Xin chào',
  'dining_type_tips': 'Bạn muốn dùng tại quán hay mang đi?',
  'checkout_type_tips': 'Bạn muốn thanh toán hay mang đi?',
  'amount_tips': 'Vui lòng nhấn "Thanh toán"',
  'cash_full_tips':
      'Mệnh giá @cash đã đạt giới hạn. Nhấn "Xác nhận" để hoàn lại tiền đã nạp. Vui lòng dùng mệnh giá hoặc phương thức thanh toán khác.',
  'cash_full_confirm': 'Xác nhận',
  'skip_button': 'Bỏ qua',
  'next_button': 'Tiếp theo',
  'suggest_title': 'Có thể bạn cũng thích',
  'repay_cash_error': 'Đã xảy ra lỗi. Vui lòng liên hệ nhân viên.',
  'network_error_tips':
      'Rất tiếc, dịch vụ tạm thời không khả dụng do sự cố mạng. Vui lòng liên hệ nhân viên hoặc hủy giao dịch.',
  'pos_notwork_tips':
      'Thiết bị POS không phản hồi. Vui lòng liên hệ nhân viên.',
  'settlement_posnosetting_error':
      'Thiết bị POS chưa được cài đặt. Vui lòng liên hệ nhân viên.',
  'pos_check_title': 'Kiểm tra trạng thái thiết bị POS',
  'pos_checking':
      'Đang kiểm tra thiết bị POS. Nếu thiết bị bất thường, quá trình sẽ tự động kết thúc sau 2 phút.',
  'pos_check_success': 'Thiết bị POS hoạt động bình thường.',
  'pos_check_failed': 'Thiết bị POS đang gặp sự cố.',
  'settlement_unexpected_error':
      'Đã xảy ra lỗi trong khi thanh toán. Vui lòng quay lại và thử lại.',
  'pos_cancel_wait_tips':
      'Giao dịch đang được xử lý nên chưa thể hủy. Vui lòng chờ, tối đa 2 phút.',
  'order_success_title': 'Thanh toán thành công',
  'order_success_tips': 'Cảm ơn quý khách.',
  'order_success_subtips': 'Tự động quay lại màn hình chính sau %% giây.',
  'origin_home': 'Về màn hình chính',
  'voucher_amount': 'Phiếu giảm giá',
  'tag_scan_network_error': 'Yêu cầu đơn hàng thất bại. Vui lòng thử lại sau.',
  'tag_scan_network_timeout':
      'Yêu cầu đơn hàng đã hết thời gian chờ. Vui lòng thử lại sau.',
  'cash_alarm_tips':
      'Mệnh giá @cash đã đạt giới hạn. Vui lòng điều chỉnh trong phần cài đặt.',
  'cash_error_staff_title': 'Vui lòng liên hệ nhân viên để kiểm tra khẩn cấp',
  'cash_error_staff_tips':
      'Máy tiền mặt đang gặp sự cố và cần được xử lý ngay.',
  'cash_error_title': 'Lỗi thiết bị',
  'cash_error_pending_title': 'Có giao dịch chưa hoàn tất',
  'go_settings_and_solve': 'Đến phần cài đặt để xử lý',
};
