const Map<String, String> zh_CN = {
  //"top_back_button":"言語",
  //"top_back_button":"首页",
  "top_back_button":"Language",

  "show_price_front":"含税",
  "tax_out":"税别",
  "tax":"含税",
  "out_tax":"外税",
  "taxout_price":"小计",
  "original_price":"原价",
  "show_original_price_front":"原价",
  "settlement_button":"结算",
  "cancle_button":"全部取消",
  "tag_title":"温馨提示",
  "tag_content":"您确定要清空购物车?",
  "tag_button_yes":"确定",
  "tag_button_no":"取消",
  "tag_checkOut":"请扫码",

  "menu_dingtype_eatin":"堂食",
  "menu_dingtype_takeout":"打包",
  "menu_dingtype_title":"欢迎光临",
  "menu_dingtype_title_tag":"请选择堂食或者打包",
  "menu_dingtype_eatin_tag":"堂食请点击此处",
  "menu_dingtype_takeout_tag":"打包请点击此处",
  "menu_ding_type_tips":"请选择",

  "cart_tag":"请选择菜品",

  "add_option_cart":"确  认",
  "settlement_total_price":"合计",
  "settlement_original_price":"原价",
  "settlement_discount":"优惠",
  "settlement_small_ticket_tag":"确认领取小票",
  //"settlement_payment_method":"可以使用以下支付方法。",
  "settlement_payment_method":"请直接投入现金或扫码。",
  "settlement_payment_method_only_cash":"请直接投入现金。",
  "settlement_payment_method_cash":"Cash",
  "settlement_payment_method_paypay":"PayPay",
  "settlement_payment_method_wechat":"WeChat Pay",
  "settlement_payment_method_alipay":"Alipay",
  "settlement_payment_method_study_cash":"现金",
  "settlement_payment_method_study_qr":"扫码支付",
  "settlement_payment_method_title":"支付方法指南",
  "settlement_back":"返回",
  "settlement_back_alertcontent":"您要取消支付吗？",
  "settlement_confirmButton":"确定支付",
  "settlement_confirmButton_yes":"要发票",
  "settlement_confirmButton_no2":"不要发票",
  "settlement_receipt_title":"发票",
  "settlement_receipt_yes":"要",
  "settlement_receipt_no":"不要",
  "settlement_orderPrice":"订单金额",
  "settlement_putMoney":"已投币    ",
  "settlement_outMoney":"找零    ",
  "settlement_print_outprice_tag":"请取出零钱,等待小票打印",
  "settlement_print_tag":"请等待小票打印",
  "settlement_print_loading_tag":"请稍候~",//，请稍候
  "settlement_noprint_tag":"请稍候~~",
  "settlement_nopayment_error":"支付失败，请选择其他方式支付",
  "settlement_scancodenoopen_error":"请选择现金支付。",
  "settlement_scancodenochange_error":"暂不支持该支付，请选择其他方式。",
  "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
  "settlement_posPay_connect_error":"自助结账终端未连接，请向工作人员咨询。",
  "settlement_posPay_error_connect_worker":"支付失败,请联系工作人员！",
  "settlement_posPay_loadint_title":"支付处理中，请稍等片刻。",
  "settlement_posPay_tips_title":"请按照pos机屏幕上显示的指示进行操作。",

  "tag_print_content_paper_shortage":"小票机缺纸，请联系工作人员",
  "tag_print_content_paper_error":"打印故障，请联系工作人员",
  "tag_print_button_yes":"已处理",
  "tag_print_button_no":"不打印",
  "show_server_error":"服务器错误请稍后重试",
  //"show_put_money_error":"请继续投币",
  "show_please_select_error":"请选择",

  "settlement_top_title_cash":"现金",
  "settlement_top_title_qr":"扫码支付",
  "settlement_top_title_card":"信用卡",
  "settlement_top_title_wallet":"电子钱包",
  "settlement_top_title_nfc":"NFC支付",

  "settlement_top_title_edy":"楽天Edy",
  "settlement_top_title_iD":"iD",
  "settlement_top_title_IC":"IC",
  "settlement_top_title_QUICPay":"QUICPay",
  "settlement_top_title_WAON":"WAON",
  "settlement_top_title_nanaco":"nanaco",

  "select_payment_dining_title":"请选择堂食还是打包",
  "select_payment_type_title":"请选择支付方式",

  "payment_success_title":"支付成功!",

  "show_storage_num_error":"此菜品库存数量不足",

  "show_del_cart_item_tag":"是否要删除商品？",
  "show_del_cart_item_yes":"删除",
  "show_del_cart_item_no":"不删除",

  "show_product_restrictions":"%%份限定",
  "show_check_tableno":"桌号：",
  "select_checkOut_tip_title":"请选择结账或者外卖",
  "select_checkOut_tip_selected":"结账",
  "checkoutScanTitle":"结账",

  "menu_option_more_multipleState":"达到最多%%个数",
  "menu_option_less_smallest":"请选择%%",
  "show_selectPay_point":"份",

  "select_selfservice_bag_title":"请选择是否需要袋子",
  "select_selfservice_nobag_title":"不要",

  "cash_change_error_title":"现金支付",
  "cash_change_error_tips_up":"现金支付机故障，暂不支持现金支付，请选择其他支付方式。",
  "cash_change_error_tips_down":"请切换到其他支付方式，或者重新启动应用。",
  "reboot_app":"重新启动",
  "change_payment":"更换支付方式",

  "cancel_order":"取消订单",
  "tag_out_money_error":"找零不足，请联系工作人员",
  "error_tips_thanks":"感谢您的操作，已联系店员处理，请稍等待。",

  "load_menu_failure_title" : "菜单加载异常。",
  "load_menu_failure_content" : "@seconds秒后将返回首页,请重试。",
  "load_menu_failure_back" : "返回首页",
  'cash_pay_checkout_tips':'支付金额更新，请继续投币。',
  "scan_order_detail_title":"订单",

  "tag_amount":"共计",
  "tag_checkout":"去结算",
  "order_start":"下单",

  "pos_report_error_tips":"非常抱歉，支付失败，请联系商家处理。",
  "pay_success_title":"支付成功\n感谢您的使用",

  "tag_cash_error":"现金机出错，请联系工作人员, 谢谢！",
  "show_order_error":"下单失败，请重试。",
  "order_network_error":"网络错误，请联系工作人员。",
  "settlement_order_error":"支付失败，请重试。",

  "cancel_button" : "取消",
  "retry_button" : "重试",
  "status_check" : "状态检查",
  "status_check_tips" : "正在检查打印机状态...",
  "status_on" : "开启",
  "status_off" : "关闭",
  "go_setting" : "去设置",

  "settlement_posnosetting_error":"POS机未设置，请联系工作人员，谢谢！",
  "pos_check_title": "POS机状态检查",
  "pos_checking": "正在检查POS机状态，请确认POS机状态是否正常，如果POS机异常情况下，检查过程将会在2分钟后自动结束。",
  "pos_check_success": "POS机状态正常",
  "pos_check_failed": "POS机状态异常",

  "skip_button":"跳过",
  "next_button":"下一步",
  "suggest_title":"您可能还喜欢",

  "pos_cancel_wait_tips": "正在交易中，暂无法取消，请稍后。最长等待时间2分钟。",
  "settlement_unexpected_error" : "支付异常，将返回上一页重新操作。",

  "order_success_title":"支付成功",
  "order_success_tips":"感谢您的下单",
  "order_success_subtips":"%%秒后自动返回首页",
  "origin_home":"返回首页",
  "voucher_amount":"代金券",

  "tag_scan_network_error":"订单请求失败，请稍后重试。",
  "tag_scan_network_timeout":"订单请求超时，请稍后重试。",

  "menu_spicy_hot_pot":"麻辣烫",

  // 麻辣烫称重 / 口味选择
  "spicy_step_start":"开始",
  "spicy_step_weigh":"称重",
  "spicy_step_soup":"汤底",
  "spicy_step_topping":"选配料",
  "spicy_step_checkout":"结账",
  "spicy_step_pay":"支付",
  "spicy_weigh_title":"请将碗放到秤上称重",
  "spicy_weigh_subtitle":"请把碗放在称重台上",
  "spicy_weigh_unit_price":"单价",
  "spicy_weigh_remeasure":"重新称重",
  "spicy_weigh_scale_disconnected":"电子秤未连接",
  "spicy_weigh_stable":"重量已稳定",
  "spicy_weigh_settling":"称重中…请等待稳定",
  "spicy_weigh_container_tip":"容器重量将在结账时扣除",
  "spicy_weigh_skip":"跳过称重",
  "spicy_weigh_waiting_stable":"等待稳定…",
  "spicy_soup_title":"请选择汤底",
  "spicy_soup_subtitle":"请点击汤底；有规格时将弹出选项",
  "spicy_soup_weigh_amount":"称重金额",
  "spicy_soup_selected_label":"已选汤底",
  "spicy_gift_select_option":"请先选择赠品选项",
  "spicy_soup_no_extra_option":"该商品暂无可选项目",
  "spicy_soup_select_options":"请选择选项",
  "spicy_soup_options_for":"请选择@name的选项",
  "spicy_soup_recommend":"推荐",
  "spicy_weigh_manual_allow_title":"手动输入设置",
  "spicy_weigh_manual_allow":"允许手动输入重量",
  "spicy_weigh_manual_input":"手动输入",
  "spicy_weigh_manual_input_title":"输入重量（g）",
  "spicy_weigh_manual_ready":"已手动输入（可进入下一步）",
  "spicy_weigh_below_min":"未达最低金额",
  "spicy_weigh_below_min_tip":"计量金额未达最低 @amount 円，请继续加菜或跳过称重",
  "spicy_weigh_min_amount_hint":"计量金额需达到 ¥@amount 以上才能进入下一步",
  "spicy_weigh_tare_hint":"已扣除容器皮重 @tare g，屏幕重量会比电子秤显示更轻",
  "spicy_mode_preparing":"正在准备称重…",

  "spicy_menu_scan_title":"扫描商品条码加入购物车",
  "spicy_menu_scan_subtitle":"也可以直接点击商品",
  "spicy_menu_scan_howto":"使用方法",
  "spicy_menu_scan_howto_title":"条码使用方法",
  "spicy_menu_scan_howto_body":"扫描条码后，商品会自动加入购物车",
  "spicy_menu_scan_weigh_reject":"称重商品请在称重步骤操作，无法在此扫码加入",
  "spicy_menu_scan_not_found":"未找到该条码对应的商品",
  "spicy_menu_scan_loading":"正在加入购物车…",

  "spicy_bowl_scan_title":"请扫盆边二维码或条码",
  "spicy_bowl_scan_subtitle":"扫描后将绑定本次订单的盆号",
  "spicy_bowl_scan_cancel":"取消",
  "spicy_bowl_scan_back":"返回",
  "spicy_bowl_scan_skip":"跳过称重",
  "spicy_bowl_table_no":"盆号：@no",

  "menu_discount_applied":"已优惠 ¥@amount",
  "menu_discount_minus":"优惠 -¥@amount",
  "menu_discount_invalid":"优惠金额不符，请重新选择优惠",

};
