const Map<String, String> zh_CN = {
        //"top_back_button":"言語",
        //"top_back_button":"首页",
        "top_back_button":"Language",

        "show_price_front":"含税",
        "tax_out":"不含税",
        "tax":"含税",
        "out_tax":"外税",
        "taxout_price":"小计",
        "original_price":"原价",
        "show_original_price_front":"原价",
        "settlement_button":"结算",
        "cancle_button":"全部取消",
        "tag_title":"温馨提示",
        "tag_content":"您确定要清空购物车?",
        "tag_button_yes":"确定",
        "tag_button_no":"取消",
        "tag_checkOut":"请扫码",

        "menu_dingtype_eatin":"堂食",
        "menu_dingtype_takeout":"打包",
        "menu_dingtype_title":"欢迎光临",
        "menu_dingtype_title_tag":"请选择堂食或者打包",
        "menu_dingtype_eatin_tag":"堂食请点击此处",
        "menu_dingtype_takeout_tag":"打包请点击此处",
        "menu_ding_type_tips":"请选择",

        "cart_tag":"请选择菜品",

        "add_option_cart":"确  认",
        "settlement_total_price":"合计",
        "settlement_original_price":"原价",
        "settlement_discount":"优惠",
        "settlement_small_ticket_tag":"确认领取小票",
        //"settlement_payment_method":"可以使用以下支付方法。",
        "settlement_payment_method":"请直接投入现金或扫码。",
        "settlement_payment_method_only_cash":"请直接投入现金。",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"现金",
        "settlement_payment_method_study_qr":"扫码支付",
        "settlement_payment_method_title":"支付方法指南",
        "settlement_back":"返回",
        "settlement_back_alertcontent":"您要取消支付吗？",
        "settlement_confirmButton":"确定支付",
        "settlement_confirmButton_yes":"要发票",
        "settlement_confirmButton_no2":"不要发票",
        "settlement_receipt_title":"发票",
        "settlement_receipt_yes":"要",
        "settlement_receipt_no":"不要",
        "settlement_orderPrice":"订单金额",
        "settlement_putMoney":"已投币    ",
        "settlement_outMoney":"找零    ",
        "settlement_print_outprice_tag":"请取出零钱,等待小票打印",
        "settlement_print_tag":"请等待小票打印",
        "settlement_print_loading_tag":"请稍候~",//，请稍候
        "settlement_noprint_tag":"请稍候~",
        "settlement_nopayment_error":"支付失败，请选择其他方式支付",
        "settlement_scancodenoopen_error":"请选择现金支付。",
        "settlement_scancodenochange_error":"暂不支持该支付，请选择其他方式。",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_connect_error":"自助结账终端未连接，请向工作人员咨询。",
        "settlement_posPay_error_connect_worker":"支付失败,请联系工作人员！",
        "settlement_posPay_loadint_title":"支付处理中，请稍等片刻。",
        "settlement_posPay_tips_title":"请按照pos机屏幕上显示的指示进行操作。",

        "tag_print_content_paper_shortage":"小票机缺纸，请联系工作人员",
        "tag_print_content_paper_error":"打印故障，请联系工作人员",
        "tag_print_button_yes":"已处理",
        "tag_print_button_no":"不打印",
        "show_server_error":"服务器错误请稍后重试",
        //"show_put_money_error":"请继续投币",
        "show_please_select_error":"请选择",

        "settlement_top_title_cash":"现金",
        "settlement_top_title_qr":"扫码支付",
        "settlement_top_title_card":"信用卡",
        "settlement_top_title_wallet":"电子钱包",
        "settlement_top_title_nfc":"NFC支付",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"请选择堂食还是打包",
        "select_payment_type_title":"请选择支付方式",

        "payment_success_title":"支付成功!",

        "show_storage_num_error":"此菜品库存数量不足",

        "show_del_cart_item_tag":"是否要删除商品？",
        "show_del_cart_item_yes":"删除",
        "show_del_cart_item_no":"不删除",

        "show_product_restrictions":"%%份限定",
        "show_check_tableno":"桌号：",
        "select_checkOut_tip_title":"请选择结账或者外卖",
        "select_checkOut_tip_selected":"结账",
        "checkoutScanTitle":"结账",

        "menu_option_more_multipleState":"达到最多%%个数",
        "menu_option_less_smallest":"请选择%%",
        "show_selectPay_point":"份",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"现金支付",
        "cash_change_error_tips_up":"现金支付机故障，暂不支持现金支付，请选择其他支付方式。",
        "cash_change_error_tips_down":"请切换到其他支付方式，或者重新启动应用。",
        "reboot_app":"重新启动",
        "change_payment":"更换支付方式",

        "cancel_order":"取消订单",
        "tag_out_money_error":"找零不足，请联系工作人员",
        "error_tips_thanks":"感谢您的操作，已联系店员处理，请稍等待。",

        "load_menu_failure_title" : "菜单加载异常。",
        "load_menu_failure_content" : "@seconds秒后将返回首页,请重试。",
        "load_menu_failure_back" : "返回首页",
        'cash_pay_checkout_tips':'支付金额更新，请继续投币。',
        "scan_order_detail_title":"订单",

        "tag_amount":"共计",
        "tag_checkout":"去结算",
        "order_start":"下单",
        "take_out":"外带",

        "pos_report_error_tips":"非常抱歉，支付失败，请联系商家处理。",
        "pay_success_title":"支付成功\n感谢您的使用",

        "tag_cash_error":"现金机出错，请联系工作人员, 谢谢！",
        "show_order_error":"下单失败，请重试。",
        "order_network_error":"网络错误，请联系工作人员。",
        "settlement_order_error":"支付失败，请重试。",
        "checkoutScanTips": "请将二维码放入扫码框内",
        "cancel_button" : "取消",
        "retry_button" : "重试",
        "status_check" : "状态检查",
        "status_check_tips" : "正在检查打印机状态...",
        "status_on" : "开启",
        "status_off" : "关闭",
        "go_setting" : "去设置",

        "payment_cash_unavailable" : "现金不可用，请选择其他支付方式。",
        "activation_error_tips" : "激活码不正确，请重新输入。",

                //Error handle message
        "cash_error_no_hardware": "现金机未连接，请联系工作人员。",
        "cash_error_busy": "处理中，请稍后再试。",
        "cash_error_no_service": "服务不可用，请联系工作人员。",
        "cash_error_illegal": "已经打开，请勿重复打开。",
        "cash_error_no_claimed": "服务不可用，请联系工作人员。",
        "cash_error_disabled": "设备已禁用，请联系工作人员。",
        "cash_error_claimed": "服务不可用，请联系工作人员。",
        "cash_error_closed": "服务不可用，请联系工作人员。",
        "cash_error_common": "发生错误，请联系工作人员。",

        "cash_error_over_dispense": "找零金额超过最大限额，请取消订单并联系商家。",
        "cash_error_over": "找零金额超过设定金额，请取消订单并联系商家。",
        "cash_error_if_error": "通信异常，请重试。",
        "cash_error_set_error": "脱机状态，请联系商家处理。",
        "cash_error_charging": "正在找零中，请稍后。",
        "cash_error_full": "找零箱已满，请联系商家。",
        "cash_error_cassette_wait": "请取出找零。",
        "cash_error_impossible": "当前状态无法执行操作，请联系商家。",
        "cash_error_deposit": "计数中，请稍后再试。",
        "cash_error_pause_deposit": "暂停计数，请联系商家处理。",

        "cash_error_open": "打开错误，请联系工作人员。",
        "cash_error_reg_bad_name": "设备名错误，请检查设备设置。",
        "cash_error_reg_prog_id": "程序ID错误，请检查设备设置。",
        "cash_error_create": "设备创建失败，请检查设备设置。",
        "cash_error_bad_if": "接口错误，请检查设备设置。",
        "cash_error_no_port": "端口未找到，请检查设备设置。",
        "cash_error_sense_thread": "传感器线程未找到，请检查设备设置。",
        "cash_error_config": "配置错误，请检查设备设置。",
        "cash_error_event_thread": "事件线程未找到，请检查设备设置。",
        "cash_error_failed_open": "打开失败，请检查设备设置。",
        "cash_error_event_class": "事件类未找到，请检查设备设置。",
        "cash_error_bad_version": "版本错误，请检查设备设置。",
        "cash_error_open_so": "SO文件未找到，请检查设备设置。",
        "cash_error_no_ported": "端口未找到，请检查设备设置。",
        "cash_error_specific": "特定错误，请检查设备设置。",
        "cash_error_unknown": "未知错误，请检查设备设置。",



        "in_shop":"堂食",
        "more_title":"更多",
        "main_page":"首页",

        "dining_welcome":"    欢 迎 光 临",
        "dining_type_tips":"     请选择堂食还是外带",
        "checkout_type_tips": "     请选择结算还是外带",
        "amount_tips":"     请点击'结算'",
        'cash_full_confirm':'确定',
        'cash_full_tips':'现金币种@cash 满了，点击\'确定\'将退还入金，请使用其他币种或者其他支付方式，也可以联系店家处理该问题，谢谢。非常抱歉给你带来不便',
        // 'cash_pay_checkout_tips':'支付金额更新，请确认并支付。',
        // "scan_order_detail_title":"订单",

        "skip_button":"跳过",
        "next_button":"下一步",
        "suggest_title":"您可能还喜欢",

        "repay_cash_error": "发生错误, 请联系工作人员。", 

        "network_error_tips":"非常抱歉，网络异常，暂时无法使用，请联系店员或者取消交易。",
        "pos_notwork_tips":"非常抱歉，POS机无响应，请联系店员处理，谢谢。",

        "settlement_posnosetting_error":"POS机未设置，请联系工作人员，谢谢！",
        "settlement_pos_disabled":"POS支付已关闭，请选择其他支付方式。",
        "pos_check_title": "POS机状态检查",
        "pos_checking": "正在检查POS机状态，请确认POS机状态是否正常，如果POS机异常情况下，检查过程将会在2分钟后自动结束。",
        "pos_check_success": "POS机状态正常",
        "pos_check_failed": "POS机状态异常",
        "pos_cancel_wait_tips": "正在交易中，暂无法取消，请稍后。最长等待时间2分钟。",

        "settlement_unexpected_error" : "支付异常，将返回上一页重新操作。",

        "order_success_title":"支付成功",
        "order_success_tips":"感谢您的下单",
        "order_success_subtips":"%%秒后自动返回首页",
        "origin_home":"返回首页",
        "voucher_amount":"代金券",

        "tag_scan_network_error":"订单请求失败，请稍后重试。",
        "tag_scan_network_timeout":"订单请求超时，请稍后重试。",

        'cash_alarm_tips':'金种@cash 已达到上限，请在设置中进行调整。',
        'cash_error_staff_title':'请店员紧急检查与处理',
        'cash_error_staff_tips':'现金机异常已触发，需立即处理',
        'cash_error_title':'故障情况',
        'cash_error_pending_title':'已入金未处理',
        'go_settings_and_solve':'去设置并处理',

  // 麻辣烫点单流程
  "menu_spicy_hot_pot":"麻辣烫",
  "spicy_step_start":"开始",
  "spicy_step_weigh":"称重",
  "spicy_step_soup":"汤底",
  "spicy_step_topping":"选配料",
  "spicy_step_checkout":"结账",
  "spicy_step_pay":"支付",
  "spicy_weigh_title":"请将碗放到秤上称重",
  "spicy_weigh_subtitle":"请把碗放在称重台上",
  "spicy_weigh_unit_price":"单价",
  "spicy_weigh_remeasure":"重新称重",
  "spicy_weigh_scale_disconnected":"电子秤未连接",
  "spicy_weigh_stable":"重量已稳定",
  "spicy_weigh_settling":"称重中…请等待稳定",
  "spicy_weigh_container_tip":"容器重量将在结账时扣除",
  "spicy_weigh_skip":"跳过称重",
  "spicy_weigh_waiting_stable":"等待稳定…",
  "spicy_soup_title":"请选择汤底",
  "spicy_soup_subtitle":"请点击汤底；有规格时将弹出选项",
  "spicy_soup_weigh_amount":"称重金额",
  "spicy_soup_selected_label":"已选汤底",
  "spicy_gift_select_option":"请先选择赠品选项",
  "spicy_query_failed":"商品查询失败，请重试",
  "spicy_no_weigh_item":"暂无称重商品",
  "spicy_select_soup_first":"请先选择汤底",
  "spicy_weigh_data_error":"称重数据异常，请重新称重",
  "spicy_weight_invalid":"重量无效，请重新称重",
  "spicy_add_cart_failed":"加入购物车失败，请重试",
  "spicy_processing":"处理中…",
  "spicy_soup_no_extra_option":"该商品暂无可选项目",
  "spicy_soup_select_options":"请选择选项",
  "spicy_soup_options_for":"请选择@name的选项",
  "spicy_soup_recommend":"推荐",
  "spicy_weigh_manual_allow_title":"手动输入设置",
  "spicy_weigh_manual_allow":"允许手动输入重量",
  "spicy_weigh_manual_input":"手动输入",
  "spicy_weigh_manual_input_title":"输入重量（g）",
  "spicy_weigh_manual_ready":"已手动输入（可进入下一步）",
  "spicy_weigh_below_min":"未达最低金额",
  "spicy_weigh_below_min_tip":"计量金额未达最低 @amount 日元，请继续加菜或跳过称重",
  "spicy_weigh_min_amount_hint":"计量金额需达到 ¥@amount 以上才能进入下一步",
  "spicy_weigh_tare_hint":"已扣除容器皮重 @tare g，屏幕重量会比电子秤显示更轻",
  "spicy_mode_preparing":"正在准备称重…",
  "spicy_menu_scan_title":"扫描商品条码加入购物车",
  "spicy_menu_scan_subtitle":"也可以直接点击商品",
  "spicy_menu_scan_howto":"使用方法",
  "spicy_menu_scan_howto_title":"条码使用方法",
  "spicy_menu_scan_howto_body":"扫描条码后，商品会自动加入购物车",
  "spicy_menu_scan_weigh_reject":"称重商品请在称重步骤操作，无法在此扫码加入",
  "spicy_menu_scan_not_found":"未找到该条码对应的商品",
  "spicy_menu_scan_loading":"正在加入购物车…",
  "spicy_bowl_scan_title":"请扫盆边二维码或条码",
  "spicy_bowl_scan_subtitle":"扫描后将绑定本次订单的盆号",
  "spicy_bowl_scan_cancel":"取消",
  "spicy_bowl_scan_back":"返回",
  "spicy_bowl_scan_skip":"跳过称重",
  "spicy_bowl_table_no":"盆号：@no",
  "menu_discount_applied":"已优惠 ¥@amount",
  "menu_discount_minus":"优惠 -¥@amount",
  "menu_discount_invalid":"优惠金额不符，请重新选择优惠",
};
