const Map<String, String> zh_CN = {
  //"top_back_button":"言語",
  //"top_back_button":"首页",
  "top_back_button":"Language",

  "show_price_front":"含税",
  "tax_out":"税别",
  "tax":"含税",
  "taxout_price":"小计",
  "original_price":"原价",
  "show_original_price_front":"原价",
  "settlement_button":"结算",
  "cancle_button":"全部取消",
  "tag_title":"温馨提示",
  "tag_content":"您确定要清空购物车?",
  "tag_button_yes":"确定",
  "tag_button_no":"取消",
  "tag_checkOut":"请扫码",

  "menu_dingtype_eatin":"堂食",
  "menu_dingtype_takeout":"打包",
  "menu_dingtype_title":"欢迎光临",
  "menu_dingtype_title_tag":"请选择堂食或者打包",
  "menu_dingtype_eatin_tag":"堂食请点击此处",
  "menu_dingtype_takeout_tag":"打包请点击此处",
  "menu_ding_type_tips":"请选择",

  "cart_tag":"请选择菜品",

  "add_option_cart":"确  认",
  "settlement_total_price":"合计",
  "settlement_original_price":"原价",
  "settlement_discount":"优惠",
  "settlement_small_ticket_tag":"确认领取小票",
  //"settlement_payment_method":"可以使用以下支付方法。",
  "settlement_payment_method":"请直接投入现金或扫码。",
  "settlement_payment_method_only_cash":"请直接投入现金。",
  "settlement_payment_method_cash":"Cash",
  "settlement_payment_method_paypay":"PayPay",
  "settlement_payment_method_wechat":"WeChat Pay",
  "settlement_payment_method_alipay":"Alipay",
  "settlement_payment_method_study_cash":"现金",
  "settlement_payment_method_study_qr":"扫码支付",
  "settlement_payment_method_title":"支付方法指南",
  "settlement_back":"返回",
  "settlement_back_alertcontent":"您要取消支付吗？",
  "settlement_confirmButton":"确定支付",
  "settlement_confirmButton_yes":"要发票",
  "settlement_confirmButton_no2":"不要发票",
  "settlement_receipt_title":"发票",
  "settlement_receipt_yes":"要",
  "settlement_receipt_no":"不要",
  "settlement_orderPrice":"订单金额",
  "settlement_putMoney":"已投币    ",
  "settlement_outMoney":"找零    ",
  "settlement_print_outprice_tag":"请取出零钱,等待小票打印",
  "settlement_print_tag":"请等待小票打印",
  "settlement_print_loading_tag":"请稍候~",//，请稍候
  "settlement_noprint_tag":"请稍候~~",
  "settlement_nopayment_error":"支付失败，请选择其他方式支付",
  "settlement_scancodenoopen_error":"请选择现金支付。",
  "settlement_scancodenochange_error":"暂不支持该支付，请选择其他方式。",
  "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
  "settlement_posPay_connect_error":"自助结账终端未连接，请向工作人员咨询。",
  "settlement_posPay_error_connect_worker":"支付失败,请联系工作人员！",
  "settlement_posPay_loadint_title":"支付处理中，请稍等片刻。",
  "settlement_posPay_tips_title":"请按照pos机屏幕上显示的指示进行操作。",

  "tag_print_content_paper_shortage":"小票机缺纸，请联系工作人员",
  "tag_print_content_paper_error":"打印故障，请联系工作人员",
  "tag_print_button_yes":"已处理",
  "tag_print_button_no":"不打印",
  "show_server_error":"服务器错误请稍后重试",
  //"show_put_money_error":"请继续投币",
  "show_please_select_error":"请选择",

  "settlement_top_title_cash":"现金",
  "settlement_top_title_qr":"扫码支付",
  "settlement_top_title_card":"信用卡",
  "settlement_top_title_wallet":"电子钱包",
  "settlement_top_title_nfc":"NFC支付",

  "settlement_top_title_edy":"楽天Edy",
  "settlement_top_title_iD":"iD",
  "settlement_top_title_IC":"IC",
  "settlement_top_title_QUICPay":"QUICPay",
  "settlement_top_title_WAON":"WAON",
  "settlement_top_title_nanaco":"nanaco",

  "select_payment_dining_title":"请选择堂食还是打包",
  "select_payment_type_title":"请选择支付方式",

  "payment_success_title":"支付成功!",

  "show_storage_num_error":"此菜品库存数量不足",

  "show_del_cart_item_tag":"是否要删除商品？",
  "show_del_cart_item_yes":"删除",
  "show_del_cart_item_no":"不删除",

  "show_product_restrictions":"%%份限定",
  "show_check_tableno":"桌号：",
  "select_checkOut_tip_title":"请选择结账或者外卖",
  "select_checkOut_tip_selected":"结账",
  "checkoutScanTitle":"结账",

  "menu_option_more_multipleState":"达到最多%%个数",
  "menu_option_less_smallest":"请选择%%",
  "show_selectPay_point":"份",

  "select_selfservice_bag_title":"请选择是否需要袋子",
  "select_selfservice_nobag_title":"不要",

  "cash_change_error_title":"现金支付",
  "cash_change_error_tips_up":"现金支付机故障，暂不支持现金支付，请选择其他支付方式。",
  "cash_change_error_tips_down":"请切换到其他支付方式，或者重新启动应用。",
  "reboot_app":"重新启动",
  "change_payment":"更换支付方式",

  "cancel_order":"取消订单",
  "tag_out_money_error":"找零不足，请联系工作人员",
  "error_tips_thanks":"感谢您的操作，已联系店员处理，请稍等待。",

  "load_menu_failure_title" : "菜单加载异常。",
  "load_menu_failure_content" : "@seconds秒后将返回首页,请重试。",
  "load_menu_failure_back" : "返回首页",
  'cash_pay_checkout_tips':'支付金额更新，请继续投币。',
  "scan_order_detail_title":"订单",

  "tag_amount":"共计",
  "tag_checkout":"去结算",
  "order_start":"下单",

  "pos_report_error_tips":"非常抱歉，支付失败，请联系商家处理。",
  "pay_success_title":"支付成功\n感谢您的使用",

  "tag_cash_error":"现金机出错，请联系工作人员, 谢谢！",
  "show_order_error":"下单失败，请重试。",
  "order_network_error":"网络错误，请联系工作人员。",
  "settlement_order_error":"支付失败，请重试。",

  "cancel_button" : "取消",
  "retry_button" : "重试",
  "status_check" : "状态检查",
  "status_check_tips" : "正在检查打印机状态...",
  "status_on" : "开启",
  "status_off" : "关闭",
  "go_setting" : "去设置",

  "settlement_posnosetting_error":"POS机未设置，请联系工作人员，谢谢！",
  "pos_check_title": "POS机状态检查",
  "pos_checking": "正在检查POS机状态，请稍候...",
  "pos_check_success": "POS机状态正常",
  "pos_check_failed": "POS机状态异常",

  "skip_button":"跳过",
  "next_button":"下一步",
  "suggest_title":"您可能还喜欢",

  "order_success_title":"下单成功",
  "order_success_tips":"感谢您的下单",
  "order_success_subtips":"%%秒后自动返回首页",
  "origin_home":"返回首页",

};
