class GString{
  //语言包 语言 key
  static String getToString(String languageCode, String stringTag) {
    // 语言包
    var languagePack;
    if (languageCode == 'JP') {
      languagePack = {
        //"top_back_button":"言語",
        //"top_back_button":"ホーム",
        "top_back_button":"Language",

        "show_price_front":"税込",
        "show_original_price_front":"定価",
        "settlement_button":"お会計",
        "cancle_button":"すべてキャンセル",
        "tag_title":"お知らせ",
        "tag_content":"ショッピングカートを空にします?",
        "tag_button_yes":"はい",
        "tag_button_no":"いいえ",
        "tag_checkOut":"QRコードをスキャンしてください",

        "menu_dingtype_eatin":"店内",
        "menu_dingtype_takeout":"テイクアウト",
        "menu_dingtype_title":"いらっしゃいませ",
        "menu_dingtype_title_tag":"店内またはテイクアウトをお選びください",
        "menu_dingtype_eatin_tag":"店内でお召し上がりのお客様はこちら",
        "menu_dingtype_takeout_tag":"テイクアウトのお客様はこちら",


        "cart_tag":"メニューをお選びください",

        "add_option_cart":"確  認",
        "settlement_total_price":"合計",
        "settlement_small_ticket_tag":"領収書が必要ですのでこちらをご注文ください",
        //"settlement_payment_method":"以下のお支払い方法をご利用いただけます。",
        "settlement_payment_method":"現金を投入するか、QRコードをスキャンしてください。",
        "settlement_payment_method_only_cash":"現金を投入してください。",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"現金",
        "settlement_payment_method_study_qr":"QRコード決済",
        "settlement_payment_method_title":"お支払い方法のガイド",
        "settlement_back":"戻る",
        "settlement_back_alertcontent":"お支払いを取り消ししますか？",
        "settlement_confirmButton":"支払い確定",
        "settlement_confirmButton_yes":"領収書発行",
        "settlement_confirmButton_no2":"支払い確定",
        "settlement_confirmButton_no":"領収書不発行",
        "settlement_receipt_title":"領収書",
        "settlement_receipt_yes":"発行する",
        "settlement_receipt_no":"発行しない",
        "settlement_orderPrice":"お支払い金額",
        "settlement_putMoney":"お預り    ",
        "settlement_outMoney":"お釣り    ",
        "settlement_print_outprice_tag":"    お釣りを取って下さい  \r\n しばらくお待ちください",
        "settlement_print_tag":"しばらくお待ちください",
        "settlement_print_loading_tag":"しばらくお待ちください",//少々お待ちください
        "settlement_noprint_tag":"しばらくお待ちください",
        "settlement_nopayment_error":"        支払いが失敗しました。  \r\n 他の支払い方法をお選ぶください。",
        "settlement_scancodenoopen_error":" 済みません、今度は現金でお願いします。",
        "settlement_scancodenochange_error":"済みません、他の支払い方法を選んでください。",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_error_connect_worker":"支払いが失敗しました。\r\n 他の支払い方法をお選ぶください。",//スタッフに連絡してください！
        "settlement_posPay_connect_error":"セルフレジは端末に接続されてません、スタフに聞いてお願いします。",
        "settlement_posPay_loadint_title":"支払処理中です、しばらくお待ち下さい。",
        "settlement_posPay_tips_title":"端末の画面に表示される指示に従って、操作してください。",

        "tag_print_content_paper_shortage":"用紙切れです、お近くのスタッフにお知らせください",
        "tag_print_content_paper_error":"故障、お近くのスタッフにお知らせください",
        "tag_print_button_yes":"処理済み",
        "tag_print_button_no":"印刷しない",

        "show_server_error":"しばらく経ってから、やり直してください",
        //"show_put_money_error":"続けてコインを入れてください",
        "show_please_select_error":"メニューをお選びください",

        "settlement_top_title_cash":"現金",
        "settlement_top_title_qr":"バーコード決済",
        "settlement_top_title_card":"クレジットカード",
        "settlement_top_title_wallet":"電子マネー",
        "settlement_top_title_nfc":"タッチ決済",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"店内または持ち帰りをお選びください",
        "select_payment_type_title":"支払い方法をお選びください",

        "payment_success_title":"支払完了いたしました",

        "show_storage_num_error":"この料理の在庫が不足しています",

        "show_del_cart_item_tag":"商品を削除しますか?",
        "show_del_cart_item_yes":"はい",
        "show_del_cart_item_no":"いいえ",

        "show_product_restrictions":"数量限定",//"""%%份限定",
        "show_check_tableno":"お席番号：",

        "select_checkOut_tip_title":"店内またはテイクアウトをお選びください",
        "select_checkOut_tip_selected":"                店内      \r\n（お食事後のお会計）",
        "checkoutScanTitle":"お会計",

        "menu_option_more_multipleState":"最大%%つまで",
        "menu_option_less_smallest":"%%をお選びください",
        "show_selectPay_point":"点",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"現金払い",
        "cash_change_error_tips_up":"現在、現金機に通障害が発生しており、現金でのお支払いはご利用いただけません。",
        "cash_change_error_tips_down":"キャッシュレスの支払い方法に変更するか、アプリを再起動してみてください。",
        "reboot_app":"アプリ再起動",
        "change_payment":"支払い方法を変更",
        "launch_error_tips":"インターネットが接続していません。ネット環境及び機器の接続状況をご確認の上、券売君アプリを再起動してください。",


        "select_option":"選択",
        "tag_checkout":"お会計",
        "show_empty_cart_item_title":"カートが空です",
        "tag_amount":"合計",

        //Error handle message
        "cash_error_no_hardware": "現金機が接続されていません。スタッフに連絡してください。", 
        "cash_error_busy": "処理中です。しばらくしてから再試行してください。", 
        "cash_error_no_service": "サービスは利用できません。スタッフに連絡してください。", 
        "cash_error_illegal": "すでに開いています。再度開かないでください。", 
        "cash_error_no_claimed": "サービスは利用できません。スタッフに連絡してください。",
        "cash_error_disabled": "デバイスが無効になっています。スタッフに連絡してください。", 
        "cash_error_claimed": "サービスは利用できません。スタッフに連絡してください。", 
        "cash_error_closed": "サービスは利用できません。スタッフに連絡してください。",
        "cash_error_common": "エラーが発生しました。スタッフに連絡してください。", 
        "cash_error_over_dispense": "お釣り金額が最大限度を超えています。注文をキャンセルし、店舗に連絡してください。", 
        "cash_error_over": "お釣り金額が設定金額を超えています。注文をキャンセルし、店舗に連絡してください。", 
        "cash_error_if_error": "通信エラーが発生しました。再試行してください。", 
        "cash_error_set_error": "オフライン状態です。店舗に連絡してください。", 
        "cash_error_charging": "お釣りを計算中です。しばらくお待ちください。",
        "cash_error_full": "お釣り箱が満杯です。店舗に連絡してください。", 
        "cash_error_cassette_wait": "お釣りを取り出してください。",
        "cash_error_impossible": "現在の状態では操作を実行できません。店舗に連絡してください。", 
        "cash_error_deposit": "カウント中です。しばらくお待ちください。", 
        "cash_error_pause_deposit": "カウントが一時停止しています。店舗に連絡してください。", 
        "cash_error_open": "オープンエラーが発生しました。スタッフに連絡してください。", 
        "cash_error_reg_bad_name": "デバイス名が間違っています。デバイス設定を確認してください。", 
        "cash_error_reg_prog_id": "プログラムIDが間違っています。デバイス設定を確認してください。", 
        "cash_error_create": "デバイスの作成に失敗しました。デバイス設定を確認してください。", 
        "cash_error_bad_if": "インターフェースエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_no_port": "ポートが見つかりません。デバイス設定を確認してください。", 
        "cash_error_sense_thread": "センサースレッドが見つかりません。デバイス設定を確認してください。", 
        "cash_error_config": "設定エラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_event_thread": "イベントスレッドが見つかりません。デバイス設定を確認してください。", 
        "cash_error_failed_open": "オープンに失敗しました。デバイス設定を確認してください。", 
        "cash_error_event_class": "イベントクラスが見つかりません。デバイス設定を確認してください。", 
        "cash_error_bad_version": "バージョンエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_open_so": "SOファイルが見つかりません。デバイス設定を確認してください。", 
        "cash_error_no_ported": "ポートが見つかりません。デバイス設定を確認してください。", 
        "cash_error_specific": "特定のエラーが発生しました。デバイス設定を確認してください。", 
        "cash_error_unknown": "不明なエラーが発生しました。デバイス設定を確認してください。",

        "cancel_order":"注文をキャンセル",
        "tag_out_money_error":"お釣りが足りません,お近くのスタッフにお知らせください",
        "error_tips_thanks":"操作ありがとうございます。処理のために店舗スタッフに連絡しました。しばらくお待ちください。",

        "load_menu_failure_title" : "メニューの読み込みに異常が発生しました。",
        "load_menu_failure_content" : "@seconds秒後にホーム画面に戻りますので、\n再度お試しください。",
        "load_menu_failure_back" : "ホームに戻る",

        "in_shop":"店内",
        "take_out":"持ち帰り",
        "more_title":"もっと見る",
        "main_page":"ホーム",

        "pay_success_title":"お支払いが成功しました\nご利用いただきありがとうございます",
        "scan_order_detail_title":"ご注文",
        "dining_welcome":"いらっしゃいませ",
        "dining_type_tips":"店内かお持ち帰りかを選択してください",
        "checkout_type_tips":"お会計かお持ち帰りかを選択してください",
        'cash_pay_checkout_tips':'お支払い金額の変更あり、改めて金額のご確認し、お支払いください。',
        'cash_full_confirm':'確定',
        'cash_full_tips':'金種@cash が上限に達しました。「確定」をクリックすると入金が返金されます。他の金種や支払い方法をご利用いただくか、店舗にお問い合わせください。ご不便をおかけして申し訳ございません。',
        "skip_button":"スキップ",
        "next_button":"進む",
        "suggest_title":"ご一緒にいかがですか",

        "repay_cash_error": "エラーが発生しました, スタッフに連絡してください。", 

      };
    }else if(languageCode == 'CH'){
      languagePack = {
        //"top_back_button":"言語",
        //"top_back_button":"首页",
        "top_back_button":"Language",

        "show_price_front":"含税",
        "show_original_price_front":"原价",
        "settlement_button":"结算",
        "cancle_button":"全部取消",
        "tag_title":"温馨提示",
        "tag_content":"您确定要清空购物车?",
        "tag_button_yes":"确定",
        "tag_button_no":"取消",
        "tag_checkOut":"请扫码",

        "menu_dingtype_eatin":"堂食",
        "menu_dingtype_takeout":"打包",
        "menu_dingtype_title":"欢迎光临",
        "menu_dingtype_title_tag":"请选择堂食或者打包",
        "menu_dingtype_eatin_tag":"堂食请点击此处",
        "menu_dingtype_takeout_tag":"打包请点击此处",

        "cart_tag":"请选择菜品",

        "add_option_cart":"确  认",
        "settlement_total_price":"合计",
        "settlement_small_ticket_tag":"确认领取小票",
        //"settlement_payment_method":"可以使用以下支付方法。",
        "settlement_payment_method":"请直接投入现金或扫码。",
        "settlement_payment_method_only_cash":"请直接投入现金。",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"现金",
        "settlement_payment_method_study_qr":"扫码支付",
        "settlement_payment_method_title":"支付方法指南",
        "settlement_back":"返回",
        "settlement_back_alertcontent":"您要取消支付吗？",
        "settlement_confirmButton":"确定支付",
        "settlement_confirmButton_yes":"要发票",
        "settlement_confirmButton_no2":"不要发票",
        "settlement_receipt_title":"发票",
        "settlement_receipt_yes":"要",
        "settlement_receipt_no":"不要",
        "settlement_orderPrice":"订单金额",
        "settlement_putMoney":"已投币    ",
        "settlement_outMoney":"找零    ",
        "settlement_print_outprice_tag":"请取出零钱,等待小票打印",
        "settlement_print_tag":"请等待小票打印",
        "settlement_print_loading_tag":"请稍候~",//，请稍候
        "settlement_noprint_tag":"请稍候~",
        "settlement_nopayment_error":"支付失败，请选择其他方式支付",
        "settlement_scancodenoopen_error":"请选择现金支付。",
        "settlement_scancodenochange_error":"暂不支持该支付，请选择其他方式。",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_connect_error":"自助结账终端未连接，请向工作人员咨询。",
        "settlement_posPay_error_connect_worker":"支付失败,请联系工作人员！",
        "settlement_posPay_loadint_title":"支付处理中，请稍等片刻。",
        "settlement_posPay_tips_title":"请按照pos机屏幕上显示的指示进行操作。",

        "tag_print_content_paper_shortage":"小票机缺纸，请联系工作人员",
        "tag_print_content_paper_error":"打印故障，请联系工作人员",
        "tag_print_button_yes":"已处理",
        "tag_print_button_no":"不打印",
        "show_server_error":"服务器错误请稍后重试",
        //"show_put_money_error":"请继续投币",
        "show_please_select_error":"请选择",

        "settlement_top_title_cash":"现金",
        "settlement_top_title_qr":"扫码支付",
        "settlement_top_title_card":"信用卡",
        "settlement_top_title_wallet":"电子钱包",
        "settlement_top_title_nfc":"NFC支付",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"请选择堂食还是打包",
        "select_payment_type_title":"请选择支付方式",

        "payment_success_title":"支付成功!",

        "show_storage_num_error":"此菜品库存数量不足",

        "show_del_cart_item_tag":"是否要删除商品？",
        "show_del_cart_item_yes":"删除",
        "show_del_cart_item_no":"不删除",

        "show_product_restrictions":"%%份限定",
        "show_check_tableno":"桌号：",
        "select_checkOut_tip_title":"请选择结账或者外卖",
        "select_checkOut_tip_selected":"结账",
        "checkoutScanTitle":"结账",

        "menu_option_more_multipleState":"最多%%个",
        "menu_option_less_smallest":"请选择%%",
        "show_selectPay_point":"份",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"现金支付",
        "cash_change_error_tips_up":"现金支付机故障，暂不支持现金支付，请选择其他支付方式。",
        "cash_change_error_tips_down":"请切换到其他支付方式，或者重新启动应用。",
        "launch_error_tips":"出现异常。请先检查网络连接，再试一次。",
        "reboot_app":"重新启动",
        "change_payment":"更换支付方式",

        "select_option":"选规格",
        "tag_checkout":"去结算",
        "show_empty_cart_item_title":"购物车空空如也",
        "tag_amount":"共计",


        //Error handle message
        "cash_error_no_hardware": "现金机未连接，请联系工作人员。",
        "cash_error_busy": "处理中，请稍后再试。",
        "cash_error_no_service": "服务不可用，请联系工作人员。",
        "cash_error_illegal": "已经打开，请勿重复打开。",
        "cash_error_no_claimed": "服务不可用，请联系工作人员。",
        "cash_error_disabled": "设备已禁用，请联系工作人员。",
        "cash_error_claimed": "服务不可用，请联系工作人员。",
        "cash_error_closed": "服务不可用，请联系工作人员。",
        "cash_error_common": "发生错误，请联系工作人员。",

        "cash_error_over_dispense": "找零金额超过最大限额，请取消订单并联系商家。",
        "cash_error_over": "找零金额超过设定金额，请取消订单并联系商家。",
        "cash_error_if_error": "通信异常，请重试。",
        "cash_error_set_error": "脱机状态，请联系商家处理。",
        "cash_error_charging": "正在找零中，请稍后。",
        "cash_error_full": "找零箱已满，请联系商家。",
        "cash_error_cassette_wait": "请取出找零。",
        "cash_error_impossible": "当前状态无法执行操作，请联系商家。",
        "cash_error_deposit": "计数中，请稍后再试。",
        "cash_error_pause_deposit": "暂停计数，请联系商家处理。",

        "cash_error_open": "打开错误，请联系工作人员。",
        "cash_error_reg_bad_name": "设备名错误，请检查设备设置。",
        "cash_error_reg_prog_id": "程序ID错误，请检查设备设置。",
        "cash_error_create": "设备创建失败，请检查设备设置。",
        "cash_error_bad_if": "接口错误，请检查设备设置。",
        "cash_error_no_port": "端口未找到，请检查设备设置。",
        "cash_error_sense_thread": "传感器线程未找到，请检查设备设置。",
        "cash_error_config": "配置错误，请检查设备设置。",
        "cash_error_event_thread": "事件线程未找到，请检查设备设置。",
        "cash_error_failed_open": "打开失败，请检查设备设置。",
        "cash_error_event_class": "事件类未找到，请检查设备设置。",
        "cash_error_bad_version": "版本错误，请检查设备设置。",
        "cash_error_open_so": "SO文件未找到，请检查设备设置。",
        "cash_error_no_ported": "端口未找到，请检查设备设置。",
        "cash_error_specific": "特定错误，请检查设备设置。",
        "cash_error_unknown": "未知错误，请检查设备设置。",


        "cancel_order":"取消订单",
        "tag_out_money_error":"找零不足，请联系工作人员",
        "error_tips_thanks":"感谢您的操作，已联系店员处理，请稍等待。",

        "load_menu_failure_title" : "菜单加载异常。",
        "load_menu_failure_content" : "@seconds秒后将返回首页,请重试。",
        "load_menu_failure_back" : "返回首页",

        "in_shop":"堂食",
        "take_out":"外带",
        "more_title":"更多",
        "main_page":"首页",

        "pay_success_title":"支付成功\n感谢您的使用",
        "scan_order_detail_title":"订单",
        "dining_welcome":"    欢 迎 光 临",
        "dining_type_tips":"     请选择堂食还是外带",
        "checkout_type_tips": "     请选择决算还是外带",
        'cash_pay_checkout_tips':'支付金额更新，请继续投币。',
        'cash_full_confirm':'确定',
        'cash_full_tips':'现金币种@cash 满了，点击\'确定\'将退还入金，请使用其他币种或者其他支付方式，也可以联系店家处理该问题，谢谢。非常抱歉给你带来不便',
        "skip_button":"跳过",
        "next_button":"下一步",
        "suggest_title":"您可能还喜欢",

        "repay_cash_error": "发生错误, 请联系工作人员。", 

      };
    }else if(languageCode == 'EN'){
      languagePack = {
        //"top_back_button":"言語",
        //"top_back_button":"Home",
        "top_back_button":"Language",

        "show_price_front":"Tax-In",
        "show_original_price_front":"Orig",
        "settlement_button":"Check Out",
        "cancle_button":"Cancel all",
        "tag_title":"Reminder",
        "tag_content":"Are you sure you want to empty the shopping cart?",
        "tag_button_yes":"Yes",
        "tag_button_no":"No",
        "tag_checkOut":"Please scan QR code.",

        "menu_dingtype_eatin":"Eat in",
        "menu_dingtype_takeout":"Take out",
        "menu_dingtype_title":"Welcome",
        "menu_dingtype_title_tag":"Choose eat-in or takeout",
        "menu_dingtype_eatin_tag":"Click here for customers who eat in the store",
        "menu_dingtype_takeout_tag":"Click here for takeaway customers",

        "cart_tag":"Please select dishes",

        "add_option_cart":"Confirm",
        "settlement_total_price":"Total",
        "settlement_small_ticket_tag":"We need a receipt, so please order us",
        //"settlement_payment_method":"Please select a payment method for your order：",
        "settlement_payment_method":"Please insert money or scan QR code.",
        "settlement_payment_method_only_cash":"Please insert money.",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"Cash",
        "settlement_payment_method_study_qr":"QR Code Payments",
        "settlement_payment_method_title":"Guide to Payment Methods",
        "settlement_back":"Back",
        "settlement_back_alertcontent":"Do you want to cancel the payment?",
        "settlement_confirmButton":"Confirm",
        "settlement_confirmButton_yes":"Have a receipt",
        "settlement_confirmButton_no":"No receipt",
        "settlement_confirmButton_no2":"No receipt",
        "settlement_receipt_title":"Receipt",
        "settlement_receipt_yes":"Yes",
        "settlement_receipt_no":"No",
        "settlement_orderPrice":"Tatol amount",
        "settlement_putMoney":"Amount paid",
        "settlement_outMoney":"Change due",
        "settlement_print_outprice_tag":"Please take your change and receipt",
        "settlement_print_tag":"Please take your receipt.",
        "settlement_print_loading_tag":"Processing……",//, please wait
        "settlement_noprint_tag":"Please wait a moment.",
        "settlement_nopayment_error":"Payment failed, please choose another payment method.",
        "settlement_scancodenoopen_error":"Please select cash payment.",
        "settlement_scancodenochange_error":"Please choose another method。",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_error_connect_worker":"Payment failed. Please contact the staff!",
        "settlement_posPay_connect_error":"The self-checkout is not connected to the terminal. Please ask the staff for assistance.",
        "settlement_posPay_loadint_title":"Payment processing. Please wait for a moment.",
        "settlement_posPay_tips_title":"Follow the instructions displayed on the terminal screen and proceed with the operation.",

        "tag_print_content_paper_shortage":"System error. Please contact our staff.",
        "tag_print_content_paper_error":"System error. Please contact our staff.",
        "tag_print_button_yes":"已处理",
        "tag_print_button_no":"不打印",
        "show_server_error":"System error. Please contact our staff.",
        //"show_put_money_error":"请继续投币",
        "show_please_select_error":"Please complete your order.",

        "settlement_top_title_cash":"Cash",
        "settlement_top_title_qr":"Code Payment",
        "settlement_top_title_card":"Credit Card",
        "settlement_top_title_wallet":"E-Wallet",
        "settlement_top_title_nfc":"Tap to pay",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"Please choose Eat in or Take out",
        "select_payment_type_title":"Please select a payment method",

        "payment_success_title":"Payment succeeded.",

        "show_storage_num_error":"Out of stock",

        "show_del_cart_item_tag":"Remove item？",
        "show_del_cart_item_yes":"Yes",
        "show_del_cart_item_no":"No",

        "show_product_restrictions":"LIMIT %%",
        "show_check_tableno":"Table No.",
        "select_checkOut_tip_title":"Choose in-store or takeout",
        "select_checkOut_tip_selected":"Check out",
        "checkoutScanTitle":"Bill",

        "menu_option_more_multipleState":"Up to %% maximum",
        "menu_option_less_smallest":"Please select %%",
        "show_selectPay_point":"",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"Cash Payment",
        "cash_change_error_tips_up":"Cash payment machine failure, cash payment is not available.",
        "cash_change_error_tips_down":"Please switch to other payment methods or restart the application.",
        "launch_error_tips":"An error has occurred. Please check your internet connection and try again.",
        "reboot_app":"Restart",
        "change_payment":"Change payment method",

        "select_option":"Option",
        "tag_checkout":"Check Out",
        "show_empty_cart_item_title":"The cart is empty",
        "tag_amount":"Total",

        //Error handle message
        "cash_error_no_hardware": "Cash machine is not connected. Please contact our staff.",
        "cash_error_busy": "Processing, please wait.",
        "cash_error_no_service": "Service is not available. Please contact our staff.",
        "cash_error_illegal": "Already open, no need to open again. Please contact our staff.",
        "cash_error_no_claimed": "Service is not available. Please contact our staff.",
        "cash_error_disabled": "Device is disabled. Please contact our staff.",
        "cash_error_claimed": "Service is not available. Please contact our staff.",
        "cash_error_closed": "Service is not available. Please contact our staff.",
        "cash_error_common": "An error occurred. Please contact our staff.",

        "cash_error_over_dispense": "Change amount exceeds the maximum limit. Please cancel the order and contact the store.",
        "cash_error_over": "Change amount exceeds the set amount. Please cancel the order and contact the store.",
        "cash_error_if_error": "Communication error occurred. Please try again.",
        "cash_error_set_error": "Offline status. Please contact our staff.",
        "cash_error_charging": "Calculating change, please wait.",
        "cash_error_full": "Change box is full. Please contact the store.",
        "cash_error_cassette_wait": "Please take out the change.",
        "cash_error_impossible": "Current operation cannot be performed. Please contact our staff.",
        "cash_error_deposit": "Calculating, please wait.",
        "cash_error_pause_deposit": "Calculating paused. Please contact our staff.",

        "cash_error_open": "Open error, please contact our staff.",
        "cash_error_reg_bad_name": "Device name is incorrect. Please check the device settings.",
        "cash_error_reg_prog_id": "Program ID is incorrect. Please check the device settings.",
        "cash_error_create": "Device creation failed. Please check the device settings.",
        "cash_error_bad_if": "Interface is incorrect. Please check the device settings.",
        "cash_error_no_port": "Port not found. Please check the device settings.",
        "cash_error_sense_thread": "Sensor thread not found. Please check the device settings.",
        "cash_error_config": "Configuration is incorrect. Please check the device settings.",
        "cash_error_event_thread": "Event thread not found. Please check the device settings.",
        "cash_error_failed_open": "Open failed. Please check the device settings.",
        "cash_error_event_class": "Event class not found. Please check the device settings.",
        "cash_error_bad_version": "Version is incorrect. Please check the device settings.",
        "cash_error_open_so": "SO file not found. Please check the device settings.",
        "cash_error_no_ported": "Port not found. Please check the device settings.",
        "cash_error_specific": "Specific error occurred. Please check the device settings.",
        "cash_error_unknown": "Unknown error occurred. Please check the device settings.",


        "cancel_order":"Cancel order",
        "tag_out_money_error":"Insufficient change, please contact the staff",
        "error_tips_thanks":"Thank you for your operation. We have contacted the staff for processing. Please wait a moment.",
        "load_menu_failure_title" : "Menu loading error.",
        "load_menu_failure_content" : "Returning to the home screen in @seconds seconds, please try again.",
        "load_menu_failure_back" : "Back to home",

        "in_shop":"Eat in",
        "take_out":"Take out",
        "more_title":"More",
        "main_page":"Home",

        "pay_success_title":"Payment Successful\nThank you for your use",
        "scan_order_detail_title":"Order",
        "dining_welcome":"Welcome",
        "dining_type_tips":"Would you like to dine in or take out",
        "checkout_type_tips": "Would you like to Check Out or take out",
        'cash_pay_checkout_tips':'Payment amount updated, please continue inserting cash.',
        'cash_full_tips':'The cash denomination of @cash has reached its limit. Click \'Confirm\' to refund the deposit. Please use other currencies or payment methods, or contact the store to address this issue. We apologize for any inconvenience caused.',
        'cash_full_confirm':'Confirm',
        "skip_button":"Skip",
        "next_button":"Next",
        "suggest_title":"You may also like",

        "repay_cash_error": "Error occurred. Please contact our staff.", 
        
      };
    }else if(languageCode == 'KO'){
      languagePack = {
        //"top_back_button":"言語",언어
        //"top_back_button":"첫장",//首页
        "top_back_button":"Language",

        "show_price_front":"세금 포함",//含税
        "show_original_price_front":"원가",
        "settlement_button":"합의",
        "cancle_button":"모두 취소",
        "tag_title":"친절한 팁",
        "tag_content":"장바구니를 비우시겠습니까?",
        "tag_button_yes":"확정",
        "tag_button_no":"취소",
        "tag_checkOut":"스캔해 주세요",//请扫码

        "menu_dingtype_eatin":"식사",//堂食
        "menu_dingtype_takeout":"테이크아웃",//打包
        "menu_dingtype_title":"환영",
        "menu_dingtype_title_tag":"매장 내 식사 또는 테이크아웃을 선택하세요.",
        "menu_dingtype_eatin_tag":"식사는 여기를 클릭하십시오",
        "menu_dingtype_takeout_tag":"테이크아웃여기를 클릭",

        "cart_tag":"요리를 선택해주세요",

        "add_option_cart":"확인",
        "settlement_total_price":"총",
        "settlement_small_ticket_tag":"영수증 확인",
        //"settlement_payment_method":"다음 지불 방법을 사용할 수 있습니다",
        "settlement_payment_method":"직접 현금을 넣거나 QR 코드를 스캔하세요.",
        "settlement_payment_method_only_cash":"현금으로 직접 입금해주세요",
        "settlement_payment_method_cash":"Cash",
        "settlement_payment_method_paypay":"PayPay",
        "settlement_payment_method_wechat":"WeChat Pay",
        "settlement_payment_method_alipay":"Alipay",
        "settlement_payment_method_study_cash":"현금",
        "settlement_payment_method_study_qr":"스캔 코드 결제",
        "settlement_payment_method_title":"결제수단 안내",
        "settlement_back":"반품",
        "settlement_back_alertcontent":"결제를 취소하시겠습니까?",
        "settlement_confirmButton":"결제 확인",
        "settlement_confirmButton_yes":"영수증 발행",
        "settlement_confirmButton_no":"결제 확인",
        "settlement_confirmButton_no2":"결제 확인",
        "settlement_receipt_title":"영수증",
        "settlement_receipt_yes":"발행",
        "settlement_receipt_no":"확인",
        "settlement_orderPrice":"주문금액",
        "settlement_putMoney":"입금완료   ",
        "settlement_outMoney":"거스름돈을 주다",
        "settlement_print_outprice_tag":"거스름돈을 꺼내고 영수증을 기다리세요",
        "settlement_print_tag":"영수증을기다리세요",
        "settlement_print_loading_tag":"처리 중...",//처리중이니 기다려주세요
        "settlement_noprint_tag":"기다리세요.",
        "settlement_nopayment_error":"결제에 실패했습니다. 다른 결제 수단을 선택하세요.",
        "settlement_scancodenoopen_error":"현금결제를 선택해주세요",
        "settlement_scancodenochange_error":"지금은 결제가 되지 않습니다. 다른 결제 수단을 선택하세요.",
        "settlement_posPay_error":"決済失敗ので、別の支払方法にて取引を実施してください。",
        "settlement_posPay_error_connect_worker":"결제가 실패했습니다. 직원에게 연락하세요.",
        "settlement_posPay_connect_error":"셀프 레지는 단말기에 연결되어 있지 않습니다. 직원에게 문의해 주세요.",
        "settlement_posPay_loadint_title":"결제 처리 중입니다. 잠시 기다려 주세요.",
        "settlement_posPay_tips_title":"단말기 화면에 표시된 지시에 따라 조작해주세요.",

        "tag_print_content_paper_shortage":"영수증 기계에 용지가 없습니다. 직원에게 문의하십시오.",
        "tag_print_content_paper_error":"인쇄 실패, 직원에게 문의하십시오.",
        "tag_print_button_yes":"처리됨",
        "tag_print_button_no":"인쇄 불가",
        "show_server_error":"서버 오류입니다. 나중에 다시 시도하십시오.",
        //"show_put_money_error":"계속 현금을 넣어주세요",
        "show_please_select_error":"선택하세요",

        "settlement_top_title_cash":"현금",
        "settlement_top_title_qr":"스캔 코드 결제",
        "settlement_top_title_card":"신용카드",
        "settlement_top_title_wallet":"전자지갑",
        "settlement_top_title_nfc":"NFC지블",

        "settlement_top_title_edy":"楽天Edy",
        "settlement_top_title_iD":"iD",
        "settlement_top_title_IC":"IC",
        "settlement_top_title_QUICPay":"QUICPay",
        "settlement_top_title_WAON":"WAON",
        "settlement_top_title_nanaco":"nanaco",

        "select_payment_dining_title":"매장 내 식사 또는 테이크아웃을 선택하세요.",
        "select_payment_type_title":"결제 방법을 선택해주세요",

        "payment_success_title":"결제 성공",

        "show_storage_num_error":"재고 부족",

        "show_del_cart_item_tag":"상품을 삭제하시겠습니까?",
        "show_del_cart_item_yes":"삭제합니다",
        "show_del_cart_item_no":"삭제하지 않음",

        "show_product_restrictions":"%%개한정판매",
        "show_check_tableno":"좌석 번호",
        "select_checkOut_tip_title":"매장 내 또는 포장 주문하시겠어요",
        "select_checkOut_tip_selected":"체크아웃",
        "checkoutScanTitle":"계산하다",

        "menu_option_more_multipleState":"최대 %%개까지",
        "menu_option_less_smallest":"%% 선택해주세요",
        "show_selectPay_point":"점",

        "select_selfservice_bag_title":"请选择是否需要袋子",
        "select_selfservice_nobag_title":"不要",

        "cash_change_error_title":"현금 결제",
        "cash_change_error_tips_up":"현재 현금 결제기에 장애가 발생하여 현금 결제를 사용할 수 없습니다.",
        "cash_change_error_tips_down":"다른 결제 방법으로 전환하거나 앱을 다시 시작하십시오.",
        "launch_error_tips":"오류가 발생했습니다. 먼저 인터넷 연결을 확인한 후 다시 시도해 주세요.",
        "reboot_app":"재시작",
        "change_payment":"결제 방법 변경",

        "select_option":"옵션",
        "tag_checkout":"계산",
        "show_empty_cart_item_title":"장바구니가 비어 있습니다",
        "tag_amount":"총액",


        //Error handle message
        "cash_error_no_hardware": "현금 결제기가 연결되어 있지 않습니다. 직원에게 문의하십시오.",
        "cash_error_busy": "처리 중입니다. 잠시 기다려 주십시오.",
        "cash_error_no_service": "서비스를 사용할 수 없습니다. 직원에게 문의하십시오.",
        "cash_error_illegal": "이미 열려 있습니다. 다시 열 필요가 없습니다. 직원에게 문의하십시오.",
        "cash_error_no_claimed": "서비스를 사용할 수 없습니다. 직원에게 문의하십시오.",
        "cash_error_disabled": "장치가 비활성화되었습니다. 직원에게 문의하십시오.",
        "cash_error_claimed": "서비스를 사용할 수 없습니다. 직원에게 문의하십시오.",
        "cash_error_closed": "서비스를 사용할 수 없습니다. 직원에게 문의하십시오.",
        "cash_error_common": "오류가 발생했습니다. 직원에게 문의하십시오.",

        "cash_error_over_dispense": "거스름돈이 최대 한도를 초과했습니다. 주문을 취소하고 가게에 문의하십시오.",
        "cash_error_over": "지정된 금액을 초과하는 거스름돈이 발생했습니다. 주문을 취소하고 가게에 문의하십시오.",
        "cash_error_if_error": "통신 오류가 발생했습니다. 다시 시도하십시오.",
        "cash_error_set_error": "오프라인 상태입니다. 직원에게 문의하십시오.",
        "cash_error_charging": "거스름돈 계산 중입니다. 잠시 기다려 주십시오.",
        "cash_error_full": "거스름돈이 가득 찼습니다. 가게에 문의하십시오.",
        "cash_error_cassette_wait": "거스름돈을 꺼내 주십시오.",
        "cash_error_impossible": "현재 작업을 수행할 수 없습니다. 직원에게 문의하십시오.",
        "cash_error_deposit": "계산 중입니다. 잠시 기다려 주십시오.",
        "cash_error_pause_deposit": "계산을 일시 중지했습니다. 직원에게 문의하십시오.",

        "cash_error_open": "열기 오류, 직원에게 문의하십시오.",
        "cash_error_reg_bad_name": "장치 이름이 잘못되었습니다. 장치 설정을 확인하십시오.",
        "cash_error_reg_prog_id": "프로그램 ID가 잘못되었습니다. 장치 설정을 확인하십시오.",
        "cash_error_create": "장치 생성에 실패했습니다. 장치 설정을 확인하십시오.",
        "cash_error_bad_if": "인터페이스가 잘못되었습니다. 장치 설정을 확인하십시오.",
        "cash_error_no_port": "포트를 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_sense_thread": "센서 스레드를 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_config": "구성이 잘못되었습니다. 장치 설정을 확인하십시오.",
        "cash_error_event_thread": "이벤트 스레드를 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_failed_open": "열기 실패. 장치 설정을 확인하십시오.",
        "cash_error_event_class": "이벤트 클래스를 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_bad_version": "버전이 잘못되었습니다. 장치 설정을 확인하십시오.",
        "cash_error_open_so": "SO 파일을 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_no_ported": "포트를 찾을 수 없습니다. 장치 설정을 확인하십시오.",
        "cash_error_specific": "특정 오류가 발생했습니다. 장치 설정을 확인하십시오.",
        "cash_error_unknown": "알 수 없는 오류가 발생했습니다. 장치 설정을 확인하십시오.",

        "cancel_order":"주문 취소",
        "tag_out_money_error":"거스름돈이 부족합니다. 직원에게 문의하십시오.",
        "error_tips_thanks":"작업 감사합니다. 처리를 위해 가게 직원에게 연락했습니다. 잠시만 기다려주세요.",

        "load_menu_failure_title" : "메뉴 로딩 오류。",
        "load_menu_failure_content" : "@seconds초 후 홈 화면으로 돌아갑니다,\n다시 시도하십시오。",
        "load_menu_failure_back" : "홈으로",

        "in_shop":"매장 식사",
        "take_out":"테이크아웃",
        "more_title":"더보기",
        "main_page":"첫장",

        "pay_success_title":"결제가 성공했습니다\n이용해 주셔서 감사합니다",
        "scan_order_detail_title":"주문",
        "dining_welcome":"어서 오세요",
        "dining_type_tips":"매장 식사 또는 테이크아웃 중 선택해 주세요",
        "checkout_type_tips": "합의 또는 테이크아웃 중 선택해 주세요",
        'cash_pay_checkout_tips':'결제 금액이 업데이트되었습니다. 계속 현금을 넣어주세요.',
        'cash_full_tips':'현금 단위 @cash원이 한도에 도달했습니다. \'확인\'을 클릭하면 입금이 환불됩니다. 다른 통화나 결제 방법을 사용하시거나 매장에 문의하여 이 문제를 해결해 주시기 바랍니다. 불편을 드려 대단히 죄송합니다',
        'cash_full_confirm':'확인',
        "skip_button":"건너뛰기",
        "next_button":"다음",
        "suggest_title":"함께 보면 좋을 것들",

        "repay_cash_error": "오류가 발생했습니다, 직원에게 문의하십시오.", 
      };
    }

    return languagePack[stringTag] ?? stringTag;
  }
}