group 'com.paycube.paycube_old'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        //classpath 'com.android.tools.build:gradle:3.5.0'
        classpath 'com.android.tools.build:gradle:7.0.4'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()

        flatDir {
            dirs project(':paycube').file('libs')
        }
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 28

    defaultConfig {
        minSdkVersion 19
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

repositories {
    flatDir {
        dirs 'libs'
    }
}

dependencies {
    //implementation(name: 'comlib', ext: 'aar')
    //api fileTree(dir: 'libs', include: ['*.aar'])
    implementation (name: 'comlib', ext: 'aar')
    implementation (name: 'commons-lang3-3.9', ext: 'jar')
    //implementation fileTree(dir: 'libs', include: ['*.aar'])
    //implementation fileTree(dir: 'libs', include: ['*.jar'])
    api 'com.android.support:appcompat-v7:28.0.0'
    api 'com.android.support.constraint:constraint-layout:1.1.3'
    api 'com.android.support:design:28.0.0'
    api 'junit:junit:4.12'
    api 'com.android.support.test:runner:1.0.2'
    api 'com.android.support.test.espresso:espresso-core:3.0.2'

}
