; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Foodorder"
#define AppName "券売君"
#define MyAppVersion "1.1.7"
#define MyAppPublisher "SmartWe Company, Inc."
#define MyAppURL "https://smartwe.co.jp/"
#define MyAppExeName "foodorder.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{E254136A-A120-4B9F-B394-F712FCC5D560}
AppName={#AppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
OutputDir=E:\App Release
OutputBaseFilename=smartwe_ticket_machine_{#MyAppVersion}
SetupIconFile=E:\a5nhg-kcvff-001.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; Check: IsNotUpgrade

[Files]
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\appset_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\audioplayers_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\cash_changer_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\charset_converter_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\connectivity_plus_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\dynamic_color_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\firebase_core_plugin.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\flutter_plugin_msprinter_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\flutter_windows.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\foodorder.exp"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\foodorder.lib"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\permission_handler_windows_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\r_get_ip_plugin.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\SQLite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Setup\*"; DestDir: "{app}\Setup"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "D:\Foodorder_mw\Foodorder_WP\build\windows\x64\runner\Release\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""
Root: HKA; Subkey: "Software\Classes\Applications\{#MyAppExeName}\SupportedTypes"; ValueType: string; ValueName: ".myp"; ValueData: ""

[Icons]
Name: "{group}\券売君"; Filename: "{app}\{#MyAppExeName}"
Name: "{userdesktop}\券売君"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; 生成证书文件
Filename: "cmd"; Parameters: "/c certutil -generateSSTFromWU roots.sst"; WorkingDir: "{app}"; Flags: runhidden waituntilterminated
; 安装证书到系统根存储
Filename: "cmd"; Parameters: "/c certutil -addstore -f root roots.sst"; WorkingDir: "{app}"; Flags: runhidden waituntilterminated
Filename: "{app}\Setup\OPOSSetup.bat"; Flags: shellexec; Check: IsNotUpgrade
;Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
Filename: "{app}\Setup\OPOSSetup.exe"; Flags: nowait postinstall runascurrentuser; Check: IsNotUpgrade

[UninstallDelete]
Type: filesandordirs; Name: "{app}"

[Code]
var
  IsUpgrade: Boolean;

function InitializeSetup(): Boolean;
begin
  // 检查注册表中是否存在升级标志
  IsUpgrade := RegKeyExists(HKEY_CURRENT_USER, 'Software\{#MyAppName}');
  Result := True;
end;

function IsNotUpgrade: Boolean;
begin
  Result := not IsUpgrade;
end;


procedure CurStepChanged(CurStep: TSetupStep);
begin
  if CurStep = ssPostInstall then
  begin
    // 安装完成后,将升级标志写入注册表
    RegWriteStringValue(HKEY_CURRENT_USER, 'Software\{#MyAppName}', 'Installed', 'Yes');
  end;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
begin
  case CurUninstallStep of
    usUninstall:
      begin
        if Exec(ExpandConstant('{app}\Setup\Cleanup.bat'), '', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
        begin
          // 批处理文件执行成功
        end
        else
        begin
          // 批处理文件执行失败
          MsgBox('Failed to execute uninstall script', mbError, MB_OK);
        end;
        // 删除注册表项
        if RegKeyExists(HKEY_CURRENT_USER, 'Software\{#MyAppName}') then
        begin
          RegDeleteKeyIncludingSubkeys(HKEY_CURRENT_USER, 'Software\{#MyAppName}');
        end;
      end;
    usPostUninstall:
      begin
        // 直接删除安装文件夹
        DelTree(ExpandConstant('{app}'), True, True, True);
      end;
  end;
end;