group 'com.hisanweb.flutter_plugin_msprinter'
version '1.0'

buildscript {
    repositories {
        google()
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        jcenter()
    }
}

apply plugin: 'com.android.library'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 16
        ndk{
            moduleName "msprintdata1"
            abiFilters   "x86","arm64-v8a", "armeabi-v7a"
        }
    }

    sourceSets {
        main {
            jni.srcDirs = []    // disable automatic ndk-build call, which ignore our Android.mk
            jniLibs.srcDir 'src/main/jniLibs'
        }
    }
    
    lintOptions {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    //noinspection GradleCompatible
    implementation 'org.apache.httpcomponents:httpcore:4.4.4'
    implementation files('src/main/jniLibs/jna.jar')
    implementation files('src/main/jniLibs/jna-platform.jar')
    implementation files('src/main/jniLibs/fastjson-1.2.46.jar')
}
